### ISSUE TITLE
Basic energy drink design

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#104]
# **Description**
**Task:** [Basic energy drink design]
**Feature:** [Items] (#6 )

This task involved creating a basic energy drink class that was intended to be a 'buff item' (an item used immediately upon pickup). An energy drink should have attributes such as a set value to increase a player's speed by. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a class for a particular type of item that cannot be stored in the inventory ('Buff item' class)
- [x] Create an Energy Drink class that implements all methods of a 'buff item' class 
- [x] Implement basic functionality: this involves defining the return values of the 'get()' methods, and defining what effect should apply to the character upon 'pickup'. 
- [x] JUnit testing of methods with a return value: Ensure that the 'get()' methods of the EnergyDrink class return the correct, expected value
- [x]  Extra task: Apply effect on player upon pickup
 
**Completion Deadline:** 21/08

# **Member**
- e.g. Jasmine (@Jas2310) (Jasmine Hong)
