### ISSUE TITLE
Player interaction with items

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#105]
# **Description**
**Task:** [Player interaction with items]
**Feature:** [Items] (#6)

This ticket involves resolving the third milestone of the Items feature ticket, which is finding a way for the player to interact with items and essentially pick them up. This also involves how the appearance of the items should change after 'pickup' on the level. 

# **Dependencies**

- [ ] Dependency 1 (#xx)
- [ ] Dependency 2 (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Creating a component of the player entity that detects collisions when the entity is created (i.e ItemPickupComponent)
- [x] Create a method of the ItemPickupComponent that handles the collisions and what to do upon collision - The unique 'pickup' method of the item should be called only if the entity in collision is an item entity
- [x] Marking the item entities for removal from the ForestGameArea.
- [x] Need to implement a dispose method to remove the item entity upon player contact.

 
**Completion Deadline:** Aug. 28/08
 
# **Member**
- Jasmine (@Jas2310)
- Divyanshu (@Div1o1 )
