### ISSUE TITLE
Spawning of Weapons

### ISSUE THREAD

**Issue by divyanshddn146** [UQcsse3200/2024-studio-1#108]
# **Description**
**Task:** Spawning of Weapons
**Feature:** Weapons

This task involves implementing the functionality to spawn various weapons, such as pickaxes, knives, and shotguns, on the game maps. These weapons will appear at random or predefined locations and will be available for players to pick up and use during gameplay. The spawning system should ensure that the weapons are evenly distributed and accessible within the game environment.
 
## **Example (optional)**
- These weapons will be randomly spawned at the map so that player can use it in game environmet

# **Dependencies**
- [x] (#27)
- [x] (#55)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design Weapon Spawning Logic in Game Map (Aug. 21)
- [x] Download and Integrate Weapon Assets (Aug. 23)
- [x] Making Weapon Entities for different weapons(Aug. 25)
- [x] Using those Entities in spawing in Map(Aug. 25)
 
**Completion Deadline:** Aug. 25
 
# **Member**
Divyansh Agarwal (divyanshddn146)
