### ISSUE TITLE
Improved PlayerStats Display

### ISSUE THREAD

**Issue by divyanshddn146** [UQcsse3200/2024-studio-1#109]
# **Description**
**Task:** Improving PlayerStats Display
**Feature:** Weapons

This task involves enhancing the existing PlayerStats display to include the number of pickaxes and shotguns collected by the character. The updated display will allow players to see the count of these specific weapons in their inventory, providing more detailed information during gameplay.

# **Dependencies**
- [x] (#27)
- [x] (#55)
- [x] (#34)
- [x] (#135) 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Make the collision system between different weapons and Character (Aug. 25)
- [x] Make events trigger after collision that updates the value of weapon count (Aug. 26)
- [x] Implement Weapon Count UI (Aug. 28)
- [x] Adding Ammo Counter UI that works when shooting and reloading
- [x] Improving weapon count and its texture 

 
**Completion Deadline:** Aug. 10
 
# **Member**
Divyansh Agarwal (divyanshddn146)
