### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#11]
# **Description**
Central point to track all game events that handles the interaction between game’s core components; characters. Weapons and animals. This feature will manage triggering and handling of events that occurs as character finds weapons, or engage with animals, or infact when users interact with the menu. This should be robust, scalable and capable of handling multiple types of interaction simultaneously. 
## SubFeature/component (optional)
- Interaction between character and weapons
- Interaction between weapons and animals
- Interaction between character and animals
- Interaction between users and menu
- Interaction between character and projectiles

## **Examples (optional)**
- **Weapon Pickup Example**: When a character moves over a sword lying on the ground, an event is triggered that removes the sword from the map and adds it to the character's inventory and hands.

- **Combat Example**: When a character uses the sword on an animal, a combat event is triggered that reduces the animal's health and triggers a corresponding animation

# **Dependencies**
-  #2 
- #3 
- #4 
- #10 
- #12 

# **Milestones**
List sub-features you intend to have done and in Master by the end of the sprint.
- [x] Interaction between character and weapons (Aug 23)
- [x] Interaction between weapons and animals (Aug 23)
- [x] Interaction between character and animals (Aug 23)
- [ ] Interaction between users and menu (Aug 23)
- [ ] Interaction between character and projectiles (Aug 23)
- [x] Testing (Aug 26)
- [x] Documentation (Aug 27)

**Completion Deadline:** Aug. 28 3pm

# **Documentation**
TBD

# **Members**
- Nadia D'Mello (@nadiadmello) 
- Manya Khosla (@manya-k)
- Jordan Cole (@Jordamnmn) 
- Vu Khanh Vy Ho  (@VuKhanhVyHo) 
- Sioryn Willett (@SIN-Willett)

**Comment by VuKhanhVyHo** [comment]
This is unnecessary. Events is part of characters and it is not neat to create new one

**Comment by The-AhmadAA** [comment]
I would suggest adding in explicit statements to indicate that events are to be implemented by any features that use them, and that this ticket is the central point for coordination. Otherwise, it looks good. Make sure to update it with links to the task tickets and documentation as they are created. This ticket is approved and you can start creating your associated task tickets.

**Comment by SIN-Willett** [comment]
Events have been essentially finalised.
