### ISSUE TITLE
ShieldPotion Implementation

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#114]
# **Description**
**Task:** [ShieldPotion](#114).
**Feature:** #6 

This task involves creating the initial implementation of the ShieldPotion class, which represents a shield potion item in the game. The ShieldPotion class will inherit from UsableItem and will eventually provide the player with temporary immunity against damage by negating the next two hits. For now, the focus will be on setting up the class structure, including attributes like charges, event listener placeholders, and basic methods. The effects of the shield potion (e.g., hit negation) will be an extra and is not intended to be completed for this first sprint.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Initial setup of ShieldPotion class with attributes and basic methods
- [x] Create an apply method with basic functionality
- [x] Junit testing of ShieldPotion class
- [x] Documentation of the ShieldPotion setup on wiki
 
**Completion Deadline:** Aug. 21
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Keagan (@keagan-stoessel)
