### ISSUE TITLE
Health items

### ISSUE THREAD

**Issue by Parasverma17** [UQcsse3200/2024-studio-1#115]
# **Description**
**Task:** [Medkit and Bandage items]
**Feature:** [Items] (#6)

This task involves to implement the health boost item like Bandage and Medkit, create respective class for Bandage and Medkit, and add functionality to increase player's health by a small boost of 20 and large boost of 100.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a class for Bandage and medkit each which extends the Usable item class
- [x] Implement functionality like return values of get() methods, pickup, drop, and apply the item to an entity
- [x] Junit testing of get() methods that return something, check if the health increases for Bandage and medkit class 
- [x] Extra task: Apply effect on player upon pickup
 
**Completion Deadline:** Aug. 26
 
# **Member**
- Paras Verma (@Parasverma17) (Paras Verma)
