### ISSUE TITLE
Projectiles - Team 2

### ISSUE THREAD

**Issue by D-avidTao** [UQcsse3200/2024-studio-1#12]
# **Description**
As a player I'd like to trigger projectiles, so that I can get feedback on my attempt to damage game entities. 

Visually, a projectile has a texture, speed and direction. These features signify the backend logic of checking for a hitbox in a straight line. In the event a hitbox is intercepted visually the projectile's texture is updated to show a collision.

Logically, the projectile includes information about its impact. Upon intercepting a hitbox the projectile's impact is inflicted on the entity. This feature depends on hittable entities. 

## SubFeature/component
-  Weapon - Projectile and Projectile - Entity interaction through events and event handlers.
-  A projectile factory that will define projectile functionality, behavior and creation.
-  Integration with weapons.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **Project Collision**: This will allow for projectile collisions with entities (inclusive of any walls), providing both visual feedback (a texture moving across the screen) and affect (damage to entities).

# **Dependencies**
List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... maaaake a new ticket and leave it unassigned for someone else to take on.

Need to be able to detect collision to apply projectile effect and or terminate projectile.
Map and levels design  - #9 
Animal - #10
Player - #3
Events - #11

Provide information on projectile texture, speed, position and direction.  
Player - #3
Weapon and combat- #2 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement projectile collision detection with Entity.  (17th August)
- [x] Create and define a hittable interface for entities. (17th August)
- [x] Create and define a projectile factory. (21st August)
- [x] Visualise projectile movement. (25th August)
- [x]  Allow projectiles to be spawned mid game. 
- [x]  Allow projectiles to be removed in game avoiding locked states. 
- [x] Test and evaluate function including disposal states. (25th August)
- [x]  Add default picture for basic projectile - manual testing and testing of loading configuration 
- [x]  Add default animation for basic projectile - manual testing
- [x]  Layer interactions between projectiles  and supporting unit testing 
- [x]  Add shogun effect for shotgun projectiles 
- [ ]  Increase compatibility for projectiles to be used in varying context including multiple animation states 
- [ ] Add multiple atlas files for projectiles to signify differing projectile contexts (increased speed, damage, etc)
- [ ]  Manual testing for animations and use of projectiles in varying context. 

**Completion Deadline:** Aug. 27

# **Extras (optional)**
- [ ]  implement projectiles with special effects 
- [ ]  implement projectiles with complex animation states 

# **Documentation**

https://github.com/UQcsse3200/2024-studio-1/wiki/Projectile 

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- David Tao (@D-avidTao) (david)
- Benjamin Rose (@brose7561) (Ben)
- Liam Morris (@notinclined ) (Mr.Plow)
- Yashwanth Raj Govindraj (@yashwanthg22) (Yashwanth Raj)

**Comment by The-AhmadAA** [comment]
You'll need to add deadlines to your milestones (make the best estimate you can) and subfeatures/components. Where are the github usernames for the rest of your team?

**Comment by The-AhmadAA** [comment]
Approved in error, please resolve the issues from my previous comment to get this ticket approved
