### ISSUE TITLE
Create the Boss Room system with the methods to activate it

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#121]
# **Description**
create sibling class to mainRoom that will be used for Boss Rooms that will spawn a Boss every 9 Rooms, after the boss is defeated, you should be able to go to the next level 

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

## **Examples (optional)**
- **Part/Feature**: Depending on the ticket, you will often want to provide some examples of how it would play out in the game. See next point for example...
- **map seed**: maps can be generated from a "seed" where there may be different attributes, e.g. island, mainland, etc.

# **Dependencies**
- Boss Animals (use a different animal as a test subject if they don't exist yet) 
- Room Switch System (just implement the current Room to be a Boss room automatically) 

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #241
- [x] create a basic Boss Room that is distinguishable from the MainRoom sister class (if there is no bosses yet, use the basic animasl) 
- [x] create the room traversal system (when at 9 room, next room is boss)
- [x] create a Boss Room spawn array 
- [x] create method to spawn Boss based on level 
- [x] create method to make the next door automatically a Boss Room (a terminal input? pressing a certain input? consult design committee on your choice)
- [x] add a flag for when the boss is complete 

**Completion Deadline:** Sep. 3rd 

# **Extras (optional)**

# **Documentation**
- [x] write documentation for Boss Rooms 

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Dhruv @dhruvanil55 
- Ela @AElanagai 
- Zack @TranHuuPhucAn
