### ISSUE TITLE
create new Map Base Code and BaseRoom code

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#122]
# **Description**
Refactor the Code to be more class based and use libgdx more

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

# **Dependencies**
- [ ] 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #136
- [x] create a wrapper class with the intent to creating Room Factories, level factories, etc
- [x] migrate assets and unneeded code from forest game area to New classes 
- [x] store animals initialisations in a Array, create a function that checks if all the animals in the room are dead 
- [x] spawn the doors based on the hashmap (including door assets, with invisible item hitbox) 

**Completion Deadline:** Sep. 3rd 

# **Documentation**
- [x] write out documentation 

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- @ElanagaiArivuchelvan 
- @TranHuuPhucAn 
- @CameronBadman
