### ISSUE TITLE
Create System for Obtaining Items with decision making 

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#124]
# **Description**
For Items the game needs to have more decision making, this means allowing for items to only spawn at end of Room( when all the animals are dead). The user should be able to pick between 2 different items, pick 1, other item should disappear, user may not pick up a item. 

# **Dependencies**
- all animals dead method 
- animals can die 

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Change the Map Generator class to generate multiple item indexes and, limit the index to the number of items in the item table 
- [x] spawn the 2 items, store them in their own instance 
- [ ] create the logic where 1 item disapears when one is picked 

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [x] create a method to kill all animals the room for testing 
- [ ] 

# **Documentation**
- [ ] write your documentation 

# **Members**
- @TranHuuPhucAn 
- @CameronBadman
