### ISSUE TITLE
Create Level factory Class to control map logic

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#125]
# **Description**
currently there is only 1 room and 1 level, with 1 tile-set, however as there will be multiple levels with multiple tilesets, bosses.

# **Dependencies**
- [x] Room class
- [x] Map class
- [ ] animal team bosses

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] create a `LevelFactory`.
- [x] create a `MainGameLevelFactory` to inject the main gameplay. 
- [x] create the logic to switch between levels.
- [x] create the basic design for map 1.
- [x] create the system to allow for the map to be changed.

**Completion Deadline:** Sep 3rd

# **Documentation**
- [x] write documentation 

# **Members**
- @ElanagaiArivuchelvan 
- @CameronBadman 
- @SIN-Willett
