### ISSUE TITLE
add a method to spawn a entity outside of the main game system into Map Factory

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#126]
# **Description**
to spawn projectiles, you need to be able to spawn a entity on demand, unlike most teams where team-6-maps controls where they spawn, projectiles needs to have more freedom, as such they need to spawn a method to spawn entities and mark them for deletion

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

# **Dependencies**
Map factory remake (refactory) 

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x]  create method to allow for entites spawned at any point in the game 
- [ ] create testing for this by implementing a button or terminal command that causes the action
- [x] create a array that will store the instacnes of these objects
- [x] add a function that will consume the array to mark the entities for deletion, don't delete them mark for deletion 

**Completion Deadline:** Sep 3rd 

# **Documentation**
- [ ] write documentation 
- 
# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- e.g. Richard (@AppleByter) (Richard Thomas)
