### ISSUE TITLE
Create a UI on maps that scale and shows the entire map

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#127]
# **Description**
Collaborate with Team 1 to create a UI that can scale easily, and doesn't clip with each other

## SubFeature/component (optional)
If the ticket contains multiple components, you should explain them in more detail here.

# **Dependencies**'

List any features on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a feature needs to be implemented and the issue does not already exist... make a new ticket and leave it unassigned for someone else to take on.

e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fix writing Ui writing to scale 
- [x] fix the padding top issue 
- [ ] ensure the map is always on the screen and works with multiple aspect ratios 

**Completion Deadline:** Sep 3rd

# **Documentation**
- [ ] write documentation 

# **Members**
- @ElanagaiArivuchelvan 
- @JigyasuMittal
