### ISSUE TITLE
Updated Character Animation

### ISSUE THREAD

**Issue by nadiadmello** [UQcsse3200/2024-studio-1#128]
# **Updated Character Animation**
**Task:** [Animation](#3).
**Feature:** [Character](#3)

Improve on the character animation. The death and damage animation frames will be introduced and displayed based on the event of an attack or depleted health status. This will require modifying the class 'PlayerAnimationController' and updating the event listener to update the animation based on the character's status. A method will also need to be added within the 'PlayerFactory' to register all the new animation frames to the AnimationRenderComponent. In addition, an animation associated with the player invincibility frame will be added, resulting in the character to flash on the screen upon an attack. All these events will also require specific event triggers.

## **Example**
- **Receiving an attack**: Upon the event of an attack, the character animation for the particular direction will be played.

# **Dependencies**
- [ ] [Invincibility frames](#67)
- [ ] Health status
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Plan out the different frames needed (Aug. 31)
- [ ] Add the required animations in 'PlayerFactory' (Sep. 1)
- [ ] Add the required event listeners/functions in 'PlayerAnimationController' (Sep. 1)
- [ ] Add the event triggers and refine the animations (Sep. 3)
- [ ] Testing (Sep. 6)
- [ ] Documentation on the wiki (Sep. 8)
 
**Completion Deadline:** Sep 8.
 
# **Documentation**
- [Character Animation](https://github.com/UQcsse3200/2024-studio-1/wiki/Character-Animations)
 
# **Member**
- Nadia D'Mello (@nadiadmello)
