### ISSUE TITLE
Implement projectiles spawning.

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#131]
# **Description**
**Task:** [Implement projectile spawning](#131).
**Feature:** [Weapon] (#118 )

Complete projectile function by implementing projectile rendering from weapon component.
 
# **Dependencies**
- [x] Inventory System and character (#3)
- [x] Weapon(#2 )
- [x] Projectile(#12 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Load projectile asset
- [ ] Spawn projectile from weapon component
- [ ] Ensure projectile can hit and deal damage to NPCs
- [ ] Ensure projectile can despawn properly
 
**Completion Deadline:** Sep. 3
 
# **Documentation**

# **Member**
- Trong Hieu Mai (Magnius001)
- Benjamin Rose (brose7561)
