### ISSUE TITLE
Gathering assets and implement melee weapon damage mechanic.

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#132]
# **Description**
**Task:** [Gathering assets and implement melee weapon damage mechanic.](#132).
**Feature:** [Weapon and Projectiles 2](#118)

This task involves two main activities: acquiring and preparing visual and audio assets for melee weapons, and implementing the core mechanic that handles how melee weapons deal damage in the game.
 
# **Dependencies**
- [x] #2 
 
# **Milestones**
- [x] Getting melee weapon assets 
- [ ] Implementing damage mechanic
- [ ] Implementing melee attack animation
 
**Completion Deadline:** Sep. 4

# **Documentation**
 TBD

# **Member**
- @thanghoang7020202 
- @Magnius001
