### ISSUE TITLE
Weapon rendering on character.

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#134]
# **Description**
**Task:** [Task Name](#3).
**Feature:** [Feature which this tasks contributes to implementing](#2)

This task focuses on ensuring that weapons are properly rendered and visually attached to characters in the game. This includes positioning, orientation, and animations that make the weapon appear naturally held and used by the character.
 
# **Dependencies**

 
# **Milestones**
- [x] Convert WeaponComponent to interact with WeaponEntity.
- [x] Create render component for weapon entity.
- [x] Add animation controller for weapon entity.
 
**Completion Deadline:** Sep. 10
 
# **Documentation**
- [Weapon Overview](https://github.com/UQcsse3200/2024-studio-1/wiki/Weapons)
 
# **Member**
- Rohan (@rohankumar17 )
- Trong Hieu (@Magnius001 )
