### ISSUE TITLE
BOSS ROOM SPAWNER 

### ISSUE THREAD

**Issue by dhruvanil55** [UQcsse3200/2024-studio-1#142]
# **Description**
**Task:** [Boss Room Spawner](#3).
**Feature:** [Create the Boss Room system with the methods to activate it #121](#2)

Implement a BossRoomSpawner class that will generate and manage Boss Rooms in the game. This class will inherit from BaseRoomSpawner and be distinguishable from the MainRoomSpawner class by creating a unique Boss Room environment. The room traversal system will be updated so that the 9th room encountered by the player is always the Boss Room. The BossRoomSpawner will include methods to spawn bosses based on the player's current level, with three different animal bosses corresponding to three levels. If no bosses are available, the system will fall back on spawning basic animals.
 
# **Dependencies**
- [x] Depends on the BaseRoomSpawner Class and the implementation of main room spawner since it would basically be a copy of         the other spawner classes but slightly different functionality.
- [x] Boss Animals spawning and implementation.
- [x] main game area which spawns the main room and boss room.
- [x] Room connections need to be set up so that the boss room is the 9th traversal.
- [x] Levels - Check which level player is in currently so that the right boss is spawned in, and be able to increment levels using stairs (with @ElanagaiArivuchelvan).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement the initial boss room spawner with basic functionality like a normal room  (Sep. 02)
- [x] Implement room traversal making boss room the 9th connection  (Sep. 03)
- [x] Implement room fresh checker to check if the player has gone through a room and if he has then don't spawn animals
in that room again (collab with @TranHuuPhucAn).
- [x] Collaborate to add finishing touches to boss room to make it have stairs, add flag to check when boss is dead to increment live  (Sep. 06)
- [x] Add Key binding to be able to go to boss room by pressing a certain key. (B - keypress)
**Completion Deadline:** Sep. 06
 
# **Documentation**

Rooms Systems Documentation (https://github.com/UQcsse3200/2024-studio-1/wiki/Room-System)
Level Map Documentation (https://github.com/UQcsse3200/2024-studio-1/wiki/Level-Map) 

# **Member**
- Dhruv Anil (@dhruvanil55)
