### ISSUE TITLE
Update player's UI

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#143]
# **Description**
**Task:** Update UI of Player's components 
**Feature:** Character #3 

Fix the UI of game, involving player's components. This involving modifying the existing PlayerInventory Display, PlayerStatsDisplay and all the other classes that are involved in displaying character's state on UI.
These tasks include:
 - fixing the fonts of player's inventory 
 - Modify how player inventory is displayed so that all the items are fixed on the screen for key binding
 - When the player picks up an item or when the player is done using the item, reflect the count of that item on display
 - Display the effects of using an inventory on the screen. For Example, display a shield over player's health bar to demonstrate the activation of shield.
 
## **Example (optional)**
- When the game starts, all the items that can be collected are displayed on the left bottom corner of the screen with the amount zero, as the game proceeds and player collects the items, the amount will increment. 
- During the game, when the player wishes to use this inventory, the effects of the item will be displayed, for example: if medkit is used the player's health will be increased to 100, if shield potion is used, then display a shield bar over player's head for the time and if bandage is used, the health bar will increase by 50%
- Moreover, when the player uses these items, the amount will reduced to show that the item no longer exits.
- 

# **Dependencies**
- [x] Items #224 
- [x] Player's interaction with Items #144 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the font (Sept 1)
- [x] Fix all the `Usable` items on the bottom left corner of the screen (Sep 2nd)
- [x] Implement Drop() method for inventory components to remove them from inventory list (task added later) (Sep 4th)
- [x] Add functionality for incrementing and decrement count as they are used (Sep 6th)
- [x] Implement functionality to display changes to player from using different items (sep 8th)
- [x] Testing (Sep 9th)
- [x] Documentation (Sep 10th)
- [x] UML / Sequence Diagrams (Sep 10th)
**Completion Deadline:** Aug. 23
 
# **Documentation**
TBA

 
# **Member**
- Manya Khosla @manya-k
