### ISSUE TITLE
Player's interaction with Item Usage

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#144]
# **Description**
**Task:** Player's interaction with Items
**Feature:** Character #3    Events #11 

Implement a system that allows the player to interact with items in the inventory using key bindings. When a specific key is pressed (e.g. '1' for the first item, '2' for the second item), the corresponding item from the inventory will be used. If the item is fully consumed, its count will be reflected in the UI. Additionally, when new items are picked up, its count should be added to the inventory and displayed on the UI in real-time. This system will provide an intuitive interface for managing items, enhancing gameplay fluidity. Items will remain visible even when their count reaches zero, ensuring players are aware of all available items.
 
## **Example (optional)**
- As the item picks up an item, its count is increased on UI and is stored in player's inventory however, the effects are not called so that player can use it later 
- To use these items, player needs to select the items position on the screen. For example, if the `MedKit` is displayed first in the list and `bandage` is second, then press `1` to use Medkit and press `2` to use Bandage. These events will trigger the apply() method and apply the effects of these items.

# **Dependencies**
- items team needs to implement apply method for each item #155 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] learn the event handling system (Sep 3rd)
- [x]  Add key binding for each item (Sep 4th)
- [x] Implement use of item if it exits in inventory and player attempts to use (Sep 5th)
- [x] Implement Testing (Sept 6th)
- [x] Refactor the code into generic form (decided later) (sept 7th)
- [x] Add Javadocs and Documentation (Sep 10th)
- [ ] Document all the testing plans 

**Completion Deadline:** Sep. 11

 
# **Documentation**
TBA

# **Member**
- Manya Khosla @manya-k
