### ISSUE TITLE
Sound effects

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#145]
# Description
Extend the Resource Service so other teams can play sound effects without having to worry about volume settings.

Handled by the resource service:
- Loading sound files
- Setting volume based on user settings
Handled by teams:
- Uploading sound files to the repo
- Deciding which files need to be loaded and when
- Playing sounds when needed

# Dependencies
None identified so far.

# Milestones
- [ ] Extend the Resource Service (3 Sep)
- [ ] Refactor existing code to use the new functionality (3-4 Sep)
- [ ] Testing with Mockito/manually (4 Sep)
- [ ] Finalise documentation (5 Sep)
- [ ] PR into main (5 Sep)

**Completion Deadline:** 5 Sep

# Documentation
In progress
