### ISSUE TITLE
implement functionality of creating multiple character

### ISSUE THREAD

**Issue by VuKhanhVyHo** [UQcsse3200/2024-studio-1#153]
# **Task Description**
**Objective:** Create two characters for selection and fix the character loading mechanism.  
**Feature:**  #164, #3 

This task aims to fix the character loading mechanism and implement methods that allow the creation of two distinct characters for users to select from.

# **Dependencies**
None.

# **Milestones**
The following steps outline the key milestones for completing this task:
- [x] Fixed the loading mechanism from the first sprint (Completed on Aug. 5)
- [x] Refactored the `PlayerFactory` to enable character creation based on user selection (Completed on Aug. 6)
- [x] Implemented methods to create two characters for user selection (Completed on Aug. 7)
- [x] Refactored the `PlayerFactory` based on the newly implemented version by Syorin (Completed on Aug. 8)
- [x] Tested and validated functionality (Completed on Aug. 9)
- [x] Updated and finalized documentation (Completed on Aug. 10)

**Completion Deadline:** Aug. 23

# **Documentation**
- [Refactor PlayerFactory](https://github.com/UQcsse3200/2024-studio-1/wiki/Refactor-the-PlayerFactory)
- [Fix the loading state mechanism](https://github.com/UQcsse3200/2024-studio-1/wiki/Loading-State-of-the-character)
- [PlayerSelection class](https://github.com/UQcsse3200/2024-studio-1/wiki/Selection-for-Players)

# **Team Member**
- Vu Khanh Vy Ho (@VuKhanhVyHo)

**Comment by VuKhanhVyHo** [comment]
Finished
