### ISSUE TITLE
Merge Projectiles with new Map Service

### ISSUE THREAD

**Issue by s4693591** [UQcsse3200/2024-studio-1#154]
# **Description**
**Task:** Merge Projectiles with new Map GameAreaService
**Feature:** [Projectile Feature](#12) and Map Feature

The new feature of having the GameAreaService allows projectiles to spawn projectile entities from within projectile classes. Merging this in another branch earlier than merge conflicts with main to allow for projectile development to continue early.

# **Dependencies**
- [x] Projectile Team
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Merge projectile branch to be up to date with changes on Maps Branch (Sep. 5)
- [x] Refactor code to work with the GameAreaService
- [x] Spawn in projectiles at proper system areas when shooting
- [x] Merge into team-6-maps
 
**Completion Deadline:** 
September 6

**Comment by s4693591** [comment]
![MapGeneratorConfirmationDiagram](https://github.com/user-attachments/assets/916a6a2d-7b20-432b-a579-7be4e5f0b4ff)
Created a diagram of MapGenerator output to actual map outlay to deduce area error was occuring
