### ISSUE TITLE
Implement shooting projectiles for Animals

### ISSUE THREAD

**Issue by justarandomnameduh** [UQcsse3200/2024-studio-1#161]
# **Description**
**Task:** Implement shooting projectiles for Animals.
**Feature:** [Enhance Animal AI Movement and Implement Boss Character](#129 )

This task involves designing and implementing shooting mechanisms for animals to create a more diverse sequence of actions for each type of animals. Projectiles coming from animals act as a way to increase difficulty of the game since the player has to be constantly moving around to avoid incoming projectiles.
 
### **1. Animations enhancement**: 
- Implement animations configuration for shooting, this could be either keeping the attack movement for original animals or creating a different animals with shooting animations.
- Avoid overlapping animations causing the animals not to be rendered or stuttering.
### **2. Shooting action enhancement**: 
- Animals can create projectile in different size and velocity. Shooting actions only triggered when the player getting in range.
- Shooting sequences and patterns like single shot, spread shot, charged shot, and shot with increasing size over time will be implemented.
### **3. Statistics enhancement**: 
- Can create projectile statistics from the animals JSON config.
- Different types or projectiles coming from animals can be manage through a base animals projectile object.

# **Dependencies**
At the time of writing this Task Ticket, most of Projectiles features have been implemented, despite the 'black box' projectile animations.

- [x] Implement projectiles spawning (#131)
- [x] Projectiles (#12)

e.g.
- [x] Projectiles animations should work as expected (without 'black box')
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement basic shooting task for animals (Sep. 5)
- [x] Improve shooting task with considerations of borders, collisions that does not work as expected (Sep. 7)
- [x] Fix current and Implement new shooting animations for animals (Sep. 9)
- [x] Testing and refinement of shooting actions and animations (Sep. 12)
 
**Completion Deadline:** September 12, 2024
 
# **Documentation**
- TBD
 
# **Member**
- Quang Minh Tien Nguyen (@justarandomnameduh)
