### ISSUE TITLE
Screens for main game loop

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#164]
# Description
Extend the flow of the game by adding different screens for different stages of progression through the game and different outcomes.

## Screens to add
- Player select (after main menu)
- Intro cutscene (after selecting a player)
- Death screen
- Win screen

# Dependencies
- Character team are providing player assets for the player select screen and will provide a way to get an asset/name for each player you can select from, these will populate the player select screen
- Character team to trigger events for death/win, these will cause navigation to the relevant screens

# Milestones
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Implement screens (7 Sep)
- [x] Make the screens look decent, using assets provided by the Character team (8 Sep)
- [x] Set up the win/death screens to open upon winning/dying (8 Sep)
- [x] Write tests, documentation (9 Sep)
- [x] PR into team branch (10 Sep)

**Completion Deadline:** 11 Sep

# Extras (optional)
- Fancy fade to black for the death screen
- Animate the players in the player select screen

# Documentation
[StaticScreen](https://github.com/UQcsse3200/2024-studio-1/wiki/StaticScreen)
[New screens](https://github.com/UQcsse3200/2024-studio-1/wiki/New-screens)

# Members
@IanP96

**Comment by IanP96** [comment]
Done, though the screens are being improved for sprint 3
