### ISSUE TITLE
Concepts and Graphic Design for Items

### ISSUE THREAD

**Issue by charlottemaherr** [UQcsse3200/2024-studio-1#18]
# **Description**
**Task:** [Concepts and Graphics Design for Items]
**Feature:** [Items](#6) 

Create graphics for health boost, speed boost and immunity items. This task also includes conceptualisation of item attributes (e.g. affect on the player, how the player may use the item, etc.) Health boosts will increase the player's health. Speed boosts will temporarily increase the player's movement speed. The immunity potion temporarily prevents the player from taking damage. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create prototype examples of items 
- [x] Discussion/decision about item attributes 
- [x] Completion of final prototype design for immunity potion, and speed and health boosts 

**Completion Deadline:** Aug. 15

# **Member**
- Keagan Stoessel (@keagan-stoessel)
