### ISSUE TITLE
Animal Directions

### ISSUE THREAD

**Issue by vsinh14** [UQcsse3200/2024-studio-1#187]
# **Implement Animal Directions **
**Task:** [Task Name](#3).
**Feature:** [Improve Movement Tasks and Bosses ](#129 )

Implement direction based animations (movement / attack etc) based on where the player character is from the npc entity. 
 

# **Dependencies**
- [x] Fixed Textures and Atlas files 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add Spritesheets for direction  (Sep. 3)
- [x] Add SpriteSheets for bosses direction based (Sep 5)
- [x] Modify Codebase (Sep. 8)
-
 
**Completion Deadline:** Sep. 10

# **Documentation**

 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Varun Sinha (@vsinh14) (@liltawe)
- Michael (@mblauberg)

**Comment by vsinh14** [comment]
Animal animations directions implemented
