### ISSUE TITLE
Animal Attack Implementation

### ISSUE THREAD

**Issue by mblauberg** [UQcsse3200/2024-studio-1#190]
# **Description**
**Task:** [Animal Attack Implementation](#190).
**Feature:** [Enhance Animal AI Movement and Implement Boss Character](#129)

This task involves implementing a robust attack system for animals in the game by creating an `AttackBehaviour` interface that defines the essential methods for attacks. An abstract class `AttackComponent` will be developed to extend the `Component` class and implement `AttackBehaviour`. This will be the foundation of all animal's attacks, leaving room for future scalability. A concrete `MeleeAttackComponent` class will then be created by extending `AttackComponent`, enabling animals to inflict damage when within a specified range of their target. Additionally, various attack effects like knockback, stun, and poison will be conceptualised, with knockback initially functional. These effects will be initialised through a `createEffects` method in `AttackComponent` using a newly developed `EffectsFactory`. The attack parameters for each animal will be defined in the `NPCs.json` configuration file, allowing flexibility and scalability for future enhancements and effects integration.
 
## **Examples**
- **Melee Attack Example**: When a bear approaches a player within 1 units of distance, the `MeleeAttackComponent` will trigger, dealing damage to the player and applying a knockback effect.
- **Effects Example**: Knockback will be implemented and to push the player back a short distance on hit. Future updates will include stun (disabling player movement briefly), poison (applying damage over time) and possibly more effects.

# **Dependencies**
- [x] All animal implementation finalised
- [x] Animal movement to be finalised (#139)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and document `AttackBehaviour` interface (Sep. 5)
- [x] Implement `AttackComponent` abstract class (Sep. 5)
- [x] Implement `EffectFactory` for initialising attack effects (Sep. 6)
- [x] Integrate knockback effect with animals using `AttackFactory` (Sep. 6)
- [x] Develop `MeleeAttackComponent` with proximity-based attack logic and implement in `NPCFactory` (Sep. 7)
- [x] Define attack parameters for each animal in `NPCs.json` config file (Sep. 7)
- [x] Initial unit tests for `AttackComponent`, `MeleeAttackComponent` and knockback effect (Sep. 10)
- [x] Documentation updates for attack component usage and configuration (Sep. 10)
 
**Completion Deadline:** Sep. 10
 
# **Documentation**
- [Attack System](../wiki/Animal-Attack-System)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Michael Blauberg (@mblauberg )
