### ISSUE TITLE
Game Saving/Loading

### ISSUE THREAD

**Issue by TriNhan-Pham** [UQcsse3200/2024-studio-1#193]
# **Description**
**Task:** [Game Saving/Loading](#3).
**Feature:** [Pause And Save](#2)

This task ticket focuses on implementing the saving/loading feature that allows players to save the game and load it back whenever they want.

# **Dependencies**
- [x] Pause Menu Interface (#151)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finish saving feature (Aug. 9)
- [ ] Finish loading feature (Aug. 10)
 
**Completion Deadline:** Aug. 10

# **Documentation**
- TBD
 
# **Member**
- Tri Nhan Pham (@TriNhan-Pham)
