### ISSUE TITLE
Main menu and Pause menu - layout

### ISSUE THREAD

**Issue by JigyasuMittal** [UQcsse3200/2024-studio-1#20]
# **Description**
**Task:** [Main menu and Pause menu- layout](#3).
**Feature:** [Main/Pause Menus](#2)

The task involves designing the layout for the main menu and pause menu of the game, which appears upon startup and during the game when player wants to pause respectively. This includes selecting and placing a background image that aligns with the game's theme, designing where the game's logo will be displayed, and organizing the placement of the menu options like "Start New Game," "Resume Game," "Settings," and "How to Play." These menus will serve as the primary interfaces for players to start, pause, and navigate through the game.
 
## **Example (optional)**
- **Visual and Functional Design of Game Menus**:  When players start the game, the main menu is the first thing they interact with. It has a nice background related to the theme of the game and clear options that make it easy to navigate. For example, clicking "Start New Game" quickly takes them into the game’s first scene. If players need to pause the game, they press 'P' to bring up the pause menu. Here, they can choose to "Save and Quit" or continue playing by selecting "Resume."
# **Dependencies**

- [x] Game logo design.
- [x] Completion and approval of background theme.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design the initial layout and navigation structure for both menus. (Aug. 19)
- [ ] Design layout including button placement and logo integration. (Aug. 21)
- [ ] Review and feedback from the design team and team 1. (Aug. 23)

**Completion Deadline:** Aug. 23

# **Documentation**
TBD
# **Member**
- Jigyasu Mittal (@JigyasuMittal )
