### ISSUE TITLE
How To Play Menu Design

### ISSUE THREAD

**Issue by TriNhan-Pham** [UQcsse3200/2024-studio-1#21]
# **Description**
**Task:** [How To Play Menu Design](#3).
**Feature:** [Main/Pause Menus](#2)

The task requires creating the layout and content for the "How to Play" menu, which will instruct players on the game's mechanics and controls. This includes selecting colors, placing text and components that matches the game's overall theme, structuring the information in a clear and user-friendly format, and utilizing icons and images for better display of instructions. The menu should include key topics such as basic controls, game objectives, the scoring system, and any special abilities or features players need to be aware of. The 'How to Play' menu will be a critical resource for new players to understand how to navigate and succeed in the game.
 
## **Example (optional)**
- **Basic Controls**: The How To Play menu explains that player can use arrow keys to navigate their character. Moreover, it also displays how a player can attack or interact with weapons or different objects in the game. 

# **Dependencies**

- [x] Game logo designed.
- [ ] Characters and weapons designed for better illustration. (Optional)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Draft clear instructions of the game mechanics, controls, objectives, and special features. (Aug. 19)
- [x] Structure and color scheme for the How To Play menu (Aug. 20)
- [x] Have a prototype with all text, icons and images filled (Aug. 22)
- [x] Review and get feedbacks (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
TBD
 
# **Member**
- Tri Nhan Pham (@TriNhan-Pham)
