### ISSUE TITLE
Start game with difficulty

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#22]
# Description
Add buttons and functionality to start a new game with a certain difficulty (**easy**, **medium**, **hard**).
- Three buttons on the main menu will **start a new game** by initialising game data and switching to the game screen. If the user already had a game in progress, game data should likely be reset. Each button will correspond to a different level of difficulty.

# Dependencies
- May depend on #20 for creation of menu buttons. This task will link the required functionality to those buttons.
- May depend on map generation #9 being completed as the chosen difficulty should affect the map complexity (number of rooms).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add difficulty buttons (19 Aug)
- [x] Pass chosen difficulty to method that initialises game screen. Use logging to ensure the correct difficulty is being chosen and matches the difficulty selected by the player (22 Aug)
- [x] Manual testing (22 Aug)
- [x] JUnit tests? - *not implemented for sprint 1, too hard to test UI components* (24 Aug)
- [ ] Update Sprint achievement form, Personal portfolio, main feature ticket, Wiki (25 Aug)
- [ ] Merge with `feature` and `main`, with pull requests (26 Aug)
 
**Completion Deadline:** 26 Aug (Sprint 1 due 28 Aug)
 
# Documentation
- [Menu design](https://github.com/UQcsse3200/2024-studio-1/wiki/Menu-design)
- [Menu features and code documentation](https://github.com/UQcsse3200/2024-studio-1/wiki/Menu)
- [User guide to starting the game](https://github.com/UQcsse3200/2024-studio-1/wiki/Starting-the-game)
 
# Member
- Ian Pinto @IanP96

**Comment by IanP96** [comment]
Updated to include difficulty selection
