### ISSUE TITLE
Bounding Hitbox for items

### ISSUE THREAD

**Issue by Div1o1** [UQcsse3200/2024-studio-1#228]
# **Description**
**Task:** Hitbox for items
**Feature:** #138 

To implement a custom hitbox class to refine the hitbox detection for collectible items in the game. This task will involve creating a new component to more accurately represent the size and shape of collectibles, ensuring precise collision detection when the player interacts with these items. The improved hitbox will ensure that collectibles are properly collected upon player contact, providing a smoother gameplay experience.
 
# **Dependencies**
Dependent to the item entities in the game area. 

- [x] [Item Entities created on the game area](#6)

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Needs to define and implement a custom hitbox class.
- [x] Integrate with all the collectible items (including newly made).
- [x] Checking the functionality.

 
# **Documentation**
- [Physics Component](https://github.com/UQcsse3200/2024-studio-1/wiki/Physics)
 
# **Member**
- Divyanshu (@Div1o1 )
