### ISSUE TITLE
Adding a Ammo Counter

### ISSUE THREAD

**Issue by divyanshddn146** [UQcsse3200/2024-studio-1#232]
# **Description**
**Task:** [To add an ammo counter so that it can keep track of ammo of shotgun](#131).
**Feature:** [Weapon] (#118 )

Complete projectile function by implementing projectile rendering from weapon component.
 
# **Dependencies**
- [x] Weapon(#2 )
- [x] Add weapons Sound Effects(#135 )
- [x] Improved Wepon UI (#109)
- [x] Collision(#34)  
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Load ammo asset
- [x] Create Ammo UI
- [x] Ensure that ammo synchronize with sound of shotgun
- [x] Ensure that ammo reloads after all bullets get used.
- [x] Ensure that ammo reappear on screen after reloading.
 
**Completion Deadline:** Sep. 8
 
# **Documentation**

# **Member**
Divyansh Agarwal (divyanshddn146)
