### ISSUE TITLE
Merge Animals with new Projectile-Maps

### ISSUE THREAD

**Issue by justarandomnameduh** [UQcsse3200/2024-studio-1#233]
# **Description**
**Task:** Merge Animals with new Projectile-Maps
**Feature:** General Projectile features and Animal Projectile features

This new feature allow projectiles to work normally (create, move, cause damage, etc.) and can be extended to be implemented for Animals. Merging this into another branch ahead of potential merge conflicts with the main branch to enable projectile development to progress sooner.

# **Dependencies**

- [ ] Projectile creations, animations, and attack components
- [ ] Animals with range attack via projectiles
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Merge 154-merge-projectile-maps into team-7-animals-projectile to be up-to-date with projectile systems. (Sep. 6)
- [ ] Create animals with projectile creation mechanism (Sep. 7)
- [ ] Implement RangeAttackComponent for animal projectile creation and extending base projectile systems to fit animal systems (Sep. 9)
- [ ] Fine-tuning triggers and directional components for better projectile animations (Sep. 10)
 
**Completion Deadline:** Sep. 10
 
# **Documentation**
- [Attack Components](https://github.com/UQcsse3200/2024-studio-1/wiki/Animal-Attack-System#attack-components)
- [Dragon - Animals with Projectile Creation](https://github.com/UQcsse3200/2024-studio-1/wiki/Animal-Attributes-and-Behaviors#dragon)
 
# **Member**
- Quang Minh Tien Nguyen (@justarandomnameduh)

**Comment by justarandomnameduh** [comment]
This issue was created to capture previous team collaboration efforts.
