### ISSUE TITLE
Refactor Player Factory for Loading Player

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#235]
# **Description**
**Task:** Refactor Player Loader
**Feature:** #3 

Reimplement loading of player so that it uses already built functions from ItemFactory and WeaponFactory and allows for smooth intergration. Move the Loading concept into a separate class 

## **Example (optional)**
Move Loading Components to a separate class and use a method call to access loading in Player factory.
Break down CreatePlayer() method into different methods to increase the usability of each method and avoid multiple different things happening in one method

# **Dependencies**

- [x] The character needs to be saved to a config file so that it can be loaded #63 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a separate branch to handle the refactoring
- [x] Create a separate class and move all the implementation to that class
- [x] Test and Refactor simultaneously 
- [x] Write Documentation

 
**Completion Deadline:** Sep 11

# **Documentation**
N/A
 
# **Member**
- Manya @manya-k
