### ISSUE TITLE
Map Graphics

### ISSUE THREAD

**Issue by AElanagai** [UQcsse3200/2024-studio-1#24]
# **Description**
**Task:** Map Graphics 
**Feature:** Maps - Team  #9 

As part of the graphics task for the map team, this task will  primarily focus on creating  a visual representation of the game map using a grid system. This involves designing and implementing a graphical interface that displays the layout of rooms, the placement of animals, and other game elements. The grid will basically be the  foundation for rendering the game's environment and will be crucial for visualizing the game's structure.
 
## **Example**
- This task would create a 15x11 grid where each cell can represent a room or part of a room. we can also Use different colors or textures to distinguish between room types or states 
- how a short gun icon in room N's grid cell, allowing players to see available items at a glance.

# **Dependencies**
<img width="852" alt="Screenshot 2024-08-15 at 8 27 27 AM" src="https://github.com/user-attachments/assets/4bf1ac6c-cee6-4b39-b42e-235e3995ec06">

- [ ] Projectiles team to visualize  paths and impacts (#12 )
- [ ] Animals and objects team to obtain their graphical assets (#17 )
- [ ] Map builder , as the grid data will rely on it for the layout and contents for each room (#9 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] #29
- [x] #28
- [x] Grid design completion (August 17)
- [x] Grid rendering methods ( August 17) 
- [ ]  Integration with map builder data (August 18)
- [ ] Animal and Items visualisation (August 20)
- [x] #56
- [ ] #111
- [ ] 90% > AT coverage 
- [ ]  Final testing
 
**Completion Deadline:** Aug. 23

 
# **Documentation**
- TBD
 
# **Member**
- Elanagai Arivuchelvan (@AElanagai ) (Ela)
- Zack
- Dhruv
