### ISSUE TITLE
Energy drink class modifications and UI element

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#240]
# **Description**
**Task:** Energy drink class modifications and UI element
**Feature:** #138

This task will involve extending the EnergyDrink class from sprint 1, to allow for different energy drink types. The different types should have different speed boost values. For example, a "Low" speed boost only applies 10% of the original base speed on to the current speed, "Medium" applies 20%, and "High" applies 30%. The class should also be extended so that energy drink effects are stackable, and the effect should stop applying when the player reaches their maximum speed. A UI element should also be created to show the player's current speed stats. As such, the speed stats help to show the user what their accumulated speed boost is so far. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Define different energy drink types and allow for these types to be specified in the item specification (Aug. 30)
- [x] Set the item effect based on the specified energy drink type (Sep. 2)
- [x] Create a speed UI element in the PlayerStatsDisplay (eg. progress bar or written text) (Sep. 5)
- [x] Successfully update the UI element upon pickup with an energy drink (Sep. 10)
- [x] JUnit testing (Sep. 10)
 
**Completion Deadline:** Sep. 11

 
# **Documentation**
- [Main description of feature](../wiki/Items)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- e.g. Jasmine(@Jas2310 )
