### ISSUE TITLE
Update Speed and Add sounds for players when get hit

### ISSUE THREAD

**Issue by VuKhanhVyHo** [UQcsse3200/2024-studio-1#248]
# **Description**
**Task:** Update Speed Configuration for Players Based on JSON File and Add Hit Sounds.
**Feature:** [Feature which this task contributes to implementing](https://github.com/UQcsse3200/2024-studio-1/issues/269)

This task involves updating the player’s speed settings based on configurations provided in JSON files and adding sound effects when the player is hit. The player's speed will be determined by the values specified in the JSON configuration, allowing for flexibility in defining different player speeds (e.g., base speed, speed modifiers) depending on various game scenarios. Additionally, hit sounds will be added to give feedback when the player is attacked.

## **Example (optional)**
- **Sound Effect**: When a player takes damage, sound effects defined in the ./assets/hit.ogg will play.

# **Dependencies**

# **Milestones**
- [x] Define methods that can read the speed's config and load into player's files. (Sept. 25)
- [x] Add the sounds for players when get hit. (Sept. 26)
- [x] Fix any bugs occurs (Sept.29)
- [x] Documentation (Oct.1)

**Completion Deadline:** Oct.1

# **Documentation**
- [Character Animations ](https://github.com/UQcsse3200/2024-studio-1/wiki/Character-Animations)

# **Member**
- Vu Khanh Vy Ho (GitHub: @VuKhanhVyHo)
