### ISSUE TITLE
Layer projectile interactions

### ISSUE THREAD

**Issue by brose7561** [UQcsse3200/2024-studio-1#249]
# **Description**

Projectiles currently collide with each other, this means that sometimes projectiles will de-spawn before hitting the player. The proposed solution is to make all projectiles fired on the same layer, ignore each other. This implementation needs to be considerate of the future implementation of having a player negate another projectile on another layer with its own. 

## **Example (optional)**

I shoot 20 projectiles at the same entity. And I'd like them all to hit the player. Note they may not all attack given the invincibility period.  

# **Dependencies**

animal 
projectile 

# **Milestones**
List of steps that need to be completed for this task.
- [x] check current implementation by writing a test for projectile collisions (sep. 15)
- [x] write the entity check condition in projectile attack component (Sep. 17)
- [x] pass original tests (Sep. 19)
- [x] merge with main 
 
**Completion Deadline:** Sep. 20

 
 
# **Member**
- Ben Rose (brose7561) (Ben)
- [justarandomnameduh](https://github.com/justarandomnameduh)
