### ISSUE TITLE
Gathering more weapon assets and improve weapon animation

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#250]
# **Description**
**Task:** [Gathering more weapon assets and improve weapon animation](#250)
**Feature:** [Weapon and Projectiles 2](#118 )

Adding assets and texture atlases for 4 more range weapon and 3 more melee weapon. Improve weapon animation to have directional atlas for "up", "down" and firing affect.
 
## **Example**
- Shotgun will have separate animation for when the player walk up

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Getting assets for ranged weapons (Sep. 14)
- [x] Getting assets for melee weapons (Sep. 15)
- [x] Adding animations (Sep. 16)
 
**Completion Deadline:** Sep. 17

# **Documentation**
- TBD
 
# **Member**
- Trong Hieu Mai (@Magnius001 )
