### ISSUE TITLE
Getting melee weapon to work

### ISSUE THREAD

**Issue by thanghoang7020202** [UQcsse3200/2024-studio-1#251]
# **Description**

**Task:** Getting melee weapon to work
**Feature:** [Weapon and Projectiles 2](#118 )

Correct implement hidden attack including concurrent management, Get correct range based on weapon type, trigger attack and damage to all enemies within range.
 
## **Example (optional)**
- **attack**: After user press space while holding a melee weapon -> attack all NPCs within range -> reset count down.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Correct add and remove enemies from the the list of target (concurrent management) (Sep. 14)
- [x] Deal damage to all enemies within range (Sep. 18)
- [ ] Customize attack damage, attack range,... based on picked up weapon. (Sep 22)
 
**Completion Deadline:** Sep 22
 
# **Documentation**
-  TBD
 
# **Member**
- Cao Quoc Thang Hoang (thanghoang7020202)
