### ISSUE TITLE
Add New Character Animation

### ISSUE THREAD

**Issue by nadiadmello** [UQcsse3200/2024-studio-1#254]
# **Add New Character Animation**
**Task:** [Animation](#269)
**Feature:** [Character](#269)

Add new character assets and basic character animation. The option for choosing a player has been introduced and new animations are needed to differentiate between the characters and align with the design document. This will require modifying the class 'PlayerAnimationController' to adhere to playing the animation based on the character. A method will also need to be added within the 'LoadPlayer' to register all the new animation frames to the AnimationRenderComponent based on the atlas file that is provided. Finally, the 'PlayerAnimationController' will need to control the new character animation.

## **Example**

# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Find and add the required character assets (Sep. 15)
- [x] Add the required animations in 'PlayerFactory' (Sep. 16)
- [x] Modify 'PlayerAnimationController' so that it can handle two characters (Sep. 20)
- [x] Add the required event listeners/functions in 'PlayerAnimationController' (Sep. 20)
- [x] Check if event triggers are needed and refine the animations (Sep. 21)
- [x] Testing (Sep. 22)
- [x] Documentation on the wiki (Sep. 22)
 
**Completion Deadline:** Sep 22.
 
# **Documentation**
- [Character Animation](https://github.com/UQcsse3200/2024-studio-1/wiki/Character-Animations)
 
# **Member**
- Nadia D'Mello (@nadiadmello)
