### ISSUE TITLE
Character Animation on Player Select Screen

### ISSUE THREAD

**Issue by nadiadmello** [UQcsse3200/2024-studio-1#255]
# **Add animation on Player Select Screen**
**Task:** [Animation]
**Feature:** [Character/Menu Screen]

Add character animation on the player select screen. The option for choosing a player has been introduced and to make the start up screen more appealing, a short dancing animation for each character can be added. This will require modifying the class 'PlayerAnimationController' to include a method for the required animation based on the character. This is dependent on the animations for the new/second character. A method will also need to be added within the 'PlayerSelectScreen' to invoke this animation.
 
## **Example**

# **Dependencies**
- [x] Animation functionality for the new players needs to be implemented before the animation on the select screen can be started.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Try adding a method in 'PlayerAnimationController' to start this animation (Sep. 20)
- [x] Ensure loading of the assets work (Sep. 21)
- [x] Add a method in 'PlayerSelectScreen' to access this and start the animation (Sep. 23)
- [x] Modify the animation to make it fun! (Sep. 28)
- [x] Testing (Sep. 29)
- [x] Documentation on the wiki (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
 
# **Member**
Nadia D'Mello (@nadiadmello)
