### ISSUE TITLE
Refactoring WeaponComponent to move all firing logics to weapon entity

### ISSUE THREAD

**Issue by divyanshddn146** [UQcsse3200/2024-studio-1#256]
# **Description**
**Task:** To Refactor WeaponComponent to move all firing logics to weapon entity
**Feature:** Weapons

This task includes creating a new class, `AllFiringLogic`, to encapsulate all firing-related logic currently present in the `WeaponComponent`. This new class will be used as a component in the `WeaponFactory` to facilitate the creation and management of weapon entities.

# **Dependencies**
- [x] (#2)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new class named AllFiringLogic. (Sep. 18)
- [x] Include properties and methods to manage firing-related logic, such as shoot, attack , ammo management, sound effects etc. (Sep. 19)
- [x] Update the WeaponFactory class to create instances of AllFiringLogic and associate it with weapon entities. (Sep. 20)
- [x] Update WeaponComponent. (Sep. 20)
 
**Completion Deadline:** Sep. 21
 
# **Member**
Divyansh Agarwal (divyanshddn146)

**Comment by Magnius001** [comment]
Remember to set the labels correctly.
