### ISSUE TITLE
Refactoring Projectile Systems for General Uses and Implementing Projectile Boss

### ISSUE THREAD

**Issue by justarandomnameduh** [UQcsse3200/2024-studio-1#261]
# **Description**
**Task:** Refactoring Projectile Systems for General Uses and Implementing Projectile Boss
**Feature:** [Improved AI, New Attack Types, and NPCs Interactions](#257)

This task focuses on improving current projectile systems so that it can be used for multiple purposes (mainly for animals' features) thus improving the game overall experience. The goal is to generalize the current projectile systems and implementing better Projectile-Entity and Projectile-Projectile interactions. This new Projectile system is then used for implementing projectile bosses with different ranged attack patterns (using projectiles).
 
## **Example (optional)**
- **Refactoring and Improving Projectiles**: Projectiles can carry different attack effects (poison, stuns, etc. which can bypass player immunity duration)
- **Implementing projectile bosses**: Boss that can do spread shots, bouncing projectiles, varying projectile moving sequences, etc.

# **Dependencies**
- [x] Layer projectile interactions (#249)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Refactoring Projectile System for general usage (Sep. 16)
- [x] Improving features of projectiles (for spread shot, directional components, etc.) (Sep. 18)
- [x] Implementing Projectile Bosses (Sep. 20)
- [x] Fine-tuning, testing and documentations (Sep. 21)
 
**Completion Deadline:** Sep. 21

# **Extras (Optional)**
List of optional features for projectile / bosses.
- [ ] Bouncing projectiles
- [ ] Projectiles' custom moving patterns (can used difficulty variables - randomize)
 
# **Documentation**
[Projectile Overview](https://github.com/UQcsse3200/2024-studio-1/wiki/Projectile)
[ProjectileFactory updated structure](https://github.com/UQcsse3200/2024-studio-1/wiki/Projectile-Structure)
[Projectile Configs](https://github.com/UQcsse3200/2024-studio-1/wiki/Projectile-Configs)
[Projectile Animations](https://github.com/UQcsse3200/2024-studio-1/wiki/Projectile-Animations)
[Add Kitsune to Animals Type](https://github.com/UQcsse3200/2024-studio-1/wiki/Animal-Attributes-and-Behaviors)
# **Member**
- Quang Minh Tien Nguyen (@justarandomnameduh)
