### ISSUE TITLE
Boss AI Improvement 

### ISSUE THREAD

**Issue by mblauberg** [UQcsse3200/2024-studio-1#264]
# **Description**
**Task:** [Boss AI Component](#3).
**Feature:** [Animals: Improved AI, New Attack Types, and NPCs Interaction](#257).

Implement a `BossAIComponent` that integrates multiple movement tasks (`ChargeTask`, `ChaseTask`, `RunAwayTask`, `WaitTask`, and `WanderTask`) and attack components (`MeleeAttackComponent`, `RangeAttackComponent`, and `AOEAttackComponent`) into a cohesive state-driven AI system. This component will utilise a state machine to manage the boss’s actions, ensuring smooth transitions between different states such as chasing, charging, running away, waiting, wandering, range attacks and area attacks, that use a combination of movement and attack components. The state machine will determine the appropriate behaviour based on game conditions, such as the player’s distance, if it's taken damage, boss health, and predefined thresholds, allowing the boss to dynamically respond to the player’s actions in real-time.
 
## **Example**
When the boss is in the `CHARGE` state, it uses the `ChargeTask` to move in a straight line towards the player's current position at the time of activation and activates the `MeleeAttackComponent`. Once the movement is completed, a `WaitTask` is activated and the `MeleeAttackComponent` is deactivated. Conversely, if the boss’ takes damage while close to the player while in a certain state, it transitions to the `RETREAT` state, using the `RunAwayTask` to create distance from the player, then transitions to a `RANGE_ATTACK` state that activates `WaitTask` and `RangeAttackComponent`. 

# **Dependencies**
- [x] `AOEAttackComponent` implemented (#268)
- [x] Boss room to be implemented and working (#142)
- [x] Bosses to be animated
- [x] `JumpTask` to be implemented (#392)
- [x] All tasks working correctly
- [x] All attack components working correctly

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a state machine diagram to be reviewed by the team (Sep. 16).
- [x] Create states within a state transition method in `BossAIComponent` (Sep 17).
- [x] Implement conditional methods that decide whether a state should be activated when none are active (Sep 17).
- [x] Create required getter methods within tasks and attack components for the update method to use to handle transitions (Sep. 18).
- [x] Implement `update()` method and other required methods for full functionality (Sep. 18).
- [x] Play test and fix `BossAIComponent` (Sep. 20).
- [x] Add the `BossAIComponent` to all bosses with differing configurations (Sep. 21).
- [x] Implement another state that is triggered once the boss's health drops to below a threshold (Sep. 22).
- [x] Create unit tests (Sep. 23).
- [ ] Document changes in wiki (Sep. 24).
 
**Completion Deadline:** Sep. 24
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Michael Blauberg (@mblauberg)
