### ISSUE TITLE
Adapt Animal NPCs into Player Characters

### ISSUE THREAD

**Issue by vsinh14** [UQcsse3200/2024-studio-1#265]
# **Description**
Currently, various animals in the game are implemented as non-playable characters (NPCs). The goal is to adapt these animals to function as playable characters (PCs) while maintaining their unique abilities and attributes. Players should be able to control animals just as they would a human or humanoid character, with distinct mechanics, abilities, and controls suited to each animal type.

# **Dependencies**
- [x] Existing NPC animal code and attributes.
- [x] Game controller and movement systems for other player characters.
- [x] UI/UX components for selecting and interacting with playable characters.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Make Animals work with the existing player system (Sep. 17)
- [x] Allow animals to be pickable on character select screen (Sep. 19)
- [x] Ensure proper collision detection and interactions (Sep. 21)
- [x] Testing and Debugging (Sep 22)
 
**Completion Deadline:** Sep. 23
 # **Extras**
- [ ] Make a build which can transform into different animals
# **Documentation**

# **Member**
- Name (GitHub Username) (Slack Handle)
- Varun Sinha (@vsinh14) (@lawliet)

**Comment by vsinh14** [comment]
Ticket already exists
