### ISSUE TITLE
Pet System for Necromancer Build 

### ISSUE THREAD

**Issue by vsinh14** [UQcsse3200/2024-studio-1#267]
# **Description**
Currently, various animals are implemented as NPCs in the game. This task involves adapting those NPC animals to function as pets that can follow, assist, and interact with the player. The pet system should support behaviors such as following the player, attacking on command, and performing special actions depending on the type of animal.
 
# **Dependencies**

- [x] Animal AI
- [x] Animal Animations
- [x] Player Characters

# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement Player Tethering  (Sep. 17)
- [x] Implement Taming/Acquisition Method  (Sep. 20)
- [x] Show pet health (Sep. 22)
- [x] Allow targeting to location(Sep. 26)
 
**Completion Deadline:** Sep. 28

# **Documentation**
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Varun Sinha (@vsinh14) (lawliet)
