### ISSUE TITLE
Character: More player Attributes, enhancing player's interaction, UI

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#269]
# **Description**
Enhance player interaction and engagement by introducing additional attributes and UI features. This includes implementing a scoring system, sound effects, new character interactions, modified key bindings, and achievements.

## **SubFeatures/components**
 1. **Add a scoring system:**  #296 
     - For each animal killed, a certain number of coins will be awarded to the player.
     - Display the accumulated coins in the UI.

2. **Spend Money**  
     - Players can trade coins for items from gambling (based on maps team's implementation of gamble room)

3. **Sound Effects for Damage**  
     - Create and implement different sound effects to enhance immersion when the player takes damage.

4. **New Character - Homeless Guy**  
   - Introduce a new character, "Homeless Guy," who interacts with the player.

5. **Modified Key Binding - Continuous Attack**  
     - When the attack key (e.g., mouse button or keyboard key) is long-pressed, the character will continuously shoot or attack until the key is released.

6. **Update UI**
   - Make UI similar to minecraft UI
   - Display scores
 
7. **Player Transformation into NPC** (collab with animals team)
  - Player can be transformed into NPC during the game 

8. **Speed for players**
  - Players have different speed attributes this time

# **Dependencies**
- Creation of Gamble Room.

# **Milestones**
- [x] #296 (Sep 30)
- [x] Spend Money (Sep 30)
- [x] Sound Effects for Damage (Sep 30)
- [x] New Character - Homeless Guy (Sep 30)
- [x] #286
- [x] Update UI (Sep 30)
- [x] Testing (Sep 30)
- [x] Documentation (Oct 2)

**Completion Deadline:** Oct 2

# **Extras (optional)**
1. **Achievements (Extra Task)**  
   - Implement an achievement system to track player progress and award them for completing specific challenges.
  

# **Documentation**
TBA

# **Members**
- @manya-k @SIN-Willett @VuKhanhVyHo @Jordamnmn @nadiadmello

**Comment by The-AhmadAA** [comment]
Looks good, go ahead and get started if you haven't already. Just be mindful of scope creep and that this feature needs to be completed during sprint 3
