### ISSUE TITLE
Choose and Download Existing Weapon Assets

### ISSUE THREAD

**Issue by thanghoang7020202** [UQcsse3200/2024-studio-1#27]
# **Description**
**Task:** [Choose and Download Existing Weapon Assets](#2).
**Feature:** [Weapons](#2)

Identify, select, and download suitable weapon assets for the melee and shotgun weapon types. These assets will be integrated into the game’s visual and combat systems.
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game. See next point for example...
- **Armour Benefits**: Players can wear different classes of armour. Armour takes damage until it breaks. Armour cannot be healed but can be replaced. If a player is wearing armour, its health is not affected when it takes damage unless the armour is broken.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] The game’s visual style and theme (#xx)
- [ ] Ensure libgdx game engine supports the selected asset formats (#xx)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Research available weapon assets that align with the game’s theme (Aug. 19)
- [ ] Download and test compatibility of melee weapon assets (Aug. 21)
- [ ] Download and test compatibility of shotgun weapon assets (Aug. 21)
 
**Completion Deadline:** Aug. 22
 
# **Documentation**
- [Weapons Design Document](../wiki/Design-Document)
- [Asset Integration Guide](../wiki/Loading-Resources)
 -[Service Locator](../wiki/Service-Locator)

# **Member**
- Rohan Kumar (rohankumar17)
- Trong Hieu Mai (Magnius001)
- Cao Quoc Thang Hoang (thanghoang7020202)
- Divyansh Agarwal (divyanshddn146)
