### ISSUE TITLE
Named Entities

### ISSUE THREAD

**Issue by SIN-Willett** [UQcsse3200/2024-studio-1#275]
# **Description**
This feature allows entities to be named, which is useful for debugging the main game area, and also for identifying an unknown entity.

# **Dependencies**
No Dependencies this can be done entirely independently of anyone else.

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Create a NameComponent (Sept. 17)
- [x] Modify EntityService to use this (Sept. 17)
- [x] Name all the entities that are created so far (Sept. 17)
- [x] Develop Testing for NameComponent and EntityService (Sept. 17)

**Completion Deadline:** Sept. 18

# **Documentation**
- [Wiki](../wiki/NamedComponent)
- ...

# **Members**
- Sioryn (@SIN-Willett ) (SINWillett)
