### ISSUE TITLE
Health item modifications and Syringe item

### ISSUE THREAD

**Issue by Parasverma17** [UQcsse3200/2024-studio-1#277]
# **Description**
**Task:** [Health item modifications and Syringe item](#3).
**Feature:** #138 

This task includes to make some modifications in the health item like Medkit and Bandage (to cap their health at 100). Also create assets for Mystery boxes and a new health item Syringe. Implement Syringe that provides player with instant health without any capping. The syringe should be implemented instantly without going into inventory.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Create different colored assets for Mystery boxes  (Sep. 4)
- [x] Create syringe design and implement it (Sep. 4)
- [x] Health adjustments for Medkit and Bandage (Sep. 5)
- [x] Update Junit testing for Medkit and bandage (Sep. 5)
- [x] Junit testing for syringe (Sep. 8)
 
**Completion Deadline:** Sep. 11

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-1/wiki/Items)
- [Items structure](https://github.com/UQcsse3200/2024-studio-1/wiki/Items-structure)

# **Member**
- Paras Verma (@Parasverma17 )
