### ISSUE TITLE
Modified Key Binding - Continuous Attack (Sep 30)

### ISSUE THREAD

**Issue by Jordamnmn** [UQcsse3200/2024-studio-1#286]
# **Description**
While holding down one of the shoot buttons, the player will continuously shoot at a set interval. This should results in the same fire rate as before but the user won't need to repeatedly tap the button to shoot.

# **Milestones**
- [x] Complete feature (Oct. 2)

# **Extras (optional)**
- [ ] Add an item that affects fire-rate
- [x] Allow melee weapons to fire continuously

# **Documentation**
- [Held inputs](https://github.com/UQcsse3200/2024-studio-1/wiki/Held-Inputs)

# **Members**
- Jordan Cole (Jordamnmn)
