### ISSUE TITLE
Refactor weapon creations to create weapons from configs file

### ISSUE THREAD

**Issue by rohankumar17** [UQcsse3200/2024-studio-1#287]
# **Description**
**Task:** Refactor weapon creations to create weapons from configs file
**Feature:** Weapons

The objective of this task is to create the configuration file to ensure it provides all necessary data for the Weapon Factory to utilize in weapon creation and usage.

# **Dependencies**
- [x] (#2)
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create a new class named WeaponConfigFile. (Sep. 19)
- [x] Include properties and methods to manage all the configuration for all weapons. (Sep. 19)
- [x] Update the WeaponFactory class to to use configuration file for weapon. (Sep. 20)
- [x] Update WeaponComponent. (Sep. 20)
 
**Completion Deadline:** Sep. 21
 
# **Member**
Rohan Kumar (rohankumar17)
