### ISSUE TITLE
Endless Mode 

### ISSUE THREAD

**Issue by AElanagai** [UQcsse3200/2024-studio-1#292]
# **Description**

Implementing of a new game mode as an alternative to the basic gameplay. This mode will use the original room traversal system but with a focus on continuous play for point accumulation. Basically, boss rooms will spawn every 8 rooms, but the player will continue to new basic rooms even after defeating a boss rather than a new level. The level structure will be simplified, primarily featuring single-door connections between rooms. 

## SubFeature/component (optional)

1. Continuous Room Generation: Implement a system for endless room creation.
2. Boss Room Spawning: Ensure boss rooms appear every 8 rooms.
3. Single-Door Room Design: Modify room generation to primarily create rooms with only one exit.
4. Point System: Develop a scoring mechanism for this mode.
5. UI Updates: Create necessary UI elements to display current score and room coun

## **Examples (optional)**
- Room Progression: Player starts in Room 1 → Room 2 → ... → Room 8 (Boss) → Room 9 → ...(endless)
- Scoring: Points could be awarded for enemies defeated, time survived, and bosses killed .(maybe??)

# **Dependencies**

- Map generation 
- Room system
- Boss room

# **Milestones**

- [ ] Implement continuous room generation for this new mode 
- [ ] Integrate boss room spawning every 8 rooms from the old traversal system
- [ ]  Develop single-door room designs 
- [ ]  Create point system 
- [ ] Integrate points to the screen along with other elements like time survived  
- [ ]  Play and test new game mode and check the point system 
 

**Completion Deadline:** 

# **Documentation**

- TBD 

# **Members**

- e.g. Dhruv Anil (@dhruvanil55)

**Comment by dhruvanil55** [comment]
didn't need
