### ISSUE TITLE
Scoring System

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#296]
# **Description**
**Task:** Scoring System .
**Feature:** Character: More player attributes, enhancing player's interaction, UI #269

This ticket focuses on developing a scoring system in the game such that whenever an animal is killed, a specific number of coins is added to the player's total. The number of coins awarded will vary depending on the strength of the animal. These coins will be usable later during the game for various purposes (e.g., purchasing items or abilities).
 
## **Example (optional)**
- When the player kills a rat, 3 coins are collected by player and added to its inventory. 
- When a kitsune is killed, 9 coins are collected by player and added to player's inventory
- 
# **Dependencies**
- [x] All the NPC must be implemented (#61 )

# **Milestones**
List of steps that need to be completed for this task.
- [x] Animal Class Modification: add strength attribute to animal and make it accessible (Sep 17)
- [x] Add event handling to add score when animal gets killer (Sep 17)
- [x] Implement a scoring class which handles adding coins, setting coin value, spending coins (Sep 18)
- [x] Update and display coins on UI (Sep 21)
- [x] Testing (Sep 22)
- [x] Documentation (Sep 23)
 
**Completion Deadline:** Oct 2

# **Documentation**
[Scoring System](https://github.com/UQcsse3200/2024-studio-1/wiki/Scoring-System)
 
# **Member**
- Manya Khosla @manya-k
