### ISSUE TITLE
Character 

### ISSUE THREAD

**Issue by VuKhanhVyHo** [UQcsse3200/2024-studio-1#3]
# **Description**
This feature must enable users to use their characters to play the game, allow players to move around the map using keyboards, and interact with objects including grab or take weapons and rewards to gain advantages and move to the next round. As character moving around, they should not go out boundaries of the screen or go through the objects to enhance the user experience.

## SubFeature/component (optional)
- Code  animations for character to move
- Add animation for Player's Death
- Save the state of the character #63 
- load a character with given information #23 #185 
- Display all the inventory on the side #45 #163 
- Will have invincibility frames #67 
- Allow the character interact with items in its inventory through key press #144 
- The effects of using inventory must be displayed on the player #144 #163 

## **Examples (optional)**
- **Part/Feature**: As users press W, the character must move upward, or press Z then players can take their knife out.
- **UI display**: the character shows up when the player starts the game and moves around to illustrate the player's actions. The character must not go through obstacle objects or out of boundaries.

# **Dependencies**
- Creation of Map #9 
- Creation of Weapon #2 
- Creation of Items #6 
-
# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Character's current state (its health and what weapon it is holding and what items it has) can be saved (Aug 26)
- [x] Character should be able to move with keys WASD around the map, does not go through boundaries or pass through obstacle object (Aug. 22)
- [x] Character can interact with some objects (maybe a few only like to grab and put down, not too complex) (Aug. 22)
- [x] A player can be loaded from pre-saved configuration (Aug 22)
- [x] Character will an amount of time between when the are hit and when they can be hit again (Aug 27)
- [x] Character's inventory is updated and displayed on GUI at all times during the game (Aug 22)
- [x] Re-implement the loading component (Sep 10)
- [x] Display Invincibility Frames (Sep 10)
- [x] Death animation (Sep 10)
- [x] Allow character to use the items through Key Press (Sep 10)
- [x] Integration and testing of all components together (Aug. 24)
- [x]  Documentation (Aug. 26)

**Completion Deadline:** Aug. 28 3pm

# **Extras (optional)**
- [x] Can develop more about the ability to interact with other objects including weapons and animals if can
- [x] Controls are mapped from a config file.

# **Documentation**
TBD

# **Members**
- Vu Khanh Vy Ho (@VuKhanhVyHo)
- Nadia D'Mello(@nadiadmello)
- Manya Khosla (@manya-k)
- Jordan Cole (@Jordamnmn)
- Sioryn Willett (@SIN-Willett )

**Comment by The-AhmadAA** [comment]
One of the subtasks, "Design and Implement the Character" will probably need to be broken down further as there are multiple elements to this, such as creation of the character entity, character visuals and animation, physics, and so on. Movement is not really a task as this is already implemented in the base game, unless you intend to significantly rework the movement mechanic.
Aside from these issues, the feature ticket structure and description are looking good,  make sure to update it with links to the task tickets and documentation as they are created. This ticket is approved and you can start creating the associated task tickets.

**Comment by VuKhanhVyHo** [comment]
Done
