### ISSUE TITLE
Achievements

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#301]
# **Description**
**Task:** Achievements.
**Feature:** #269 

Develop an Achievements Tracking Component that constantly monitors the player's current stats and inventory. When player completes certain challenges, a badge is awarded to them. This will help in providing real-time feedback and rewards to players based on their in-game accomplishments. These achievements will be permanently stored with the player.

**Subtasks:**
1. **Design Achievements System:**
   - Define the criteria for various achievements .
   - Determine the corresponding events to be triggered when criteria are met.
   - Plan how achievements will be displayed or communicated to the player.

2. **Implement Achievements Component:**
   - Create the `AchievementsComponent` class that will be attached to the player entity.
   - Add fields to track necessary stats (e.g., weapons collected, enemies killed).
   - Implement methods to update stats based on in-game actions.

3. **Event Listeners and Triggers:**
   - Implement logic to check if achievement criteria are met and trigger appropriate events when they are.

4. **Saving**
   - Save all the badges collected permanently in the game so that every time the game is restarted, the badges collected in previous games are rendered.
.

## **Example (optional)**
- if player is kills ten animals, they will be awarded a badge 
- If player is able to kill the boss without using any items throughout the game, they will be award another badge

# **Dependencies**
- [x] implementation of rooms #8 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design Achievements System (Sep 21)
- [x] Implement Achievements Component (Sep 25)
- [x] Event Listeners and Triggers (Sep 25)
- [x] Saving (Sep 27)
- [x] Testing (Sep 30)
- [x] Documentation (Oct 1)
 
**Completion Deadline:** Oct 2

 
# **Documentation**
- TBA
 
# **Member**
- Manya @manya-k 
- Jas @Jas2310
