### ISSUE TITLE
Fix Damage Buff

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#307]
# **Description**
**Task:** Fix Damage Buff #307
**Feature:** Item Enhancement and Expansion #276

Fix the Damage Buff implementation so that it properly increases the projectile damage of the player when applied. This involves modifying the CombatStatsComponent to ensure that the buff correctly influences projectile damage, along with thorough testing to ensure functionality. Additionally, a new PNG asset for the damage buff needs to be created, as the current one is a temporary placeholder.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and create pixel PNG asset for Damage Buff 
- [x] Modify `CombatStatsComponent` to ensure projectile damage is increased with regards to player buff damage 
- [x] Implement unit testing

**Completion Deadline:** Sep. 19

# **Documentation**
TBD
 
# **Member**
- Keagan Stoessel (@keagan-stoessel)
