### ISSUE TITLE
Change Player Item Interaction

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#308]
# **Description**
**Task:** Change Player Item Interaction #308
**Feature:** Item Enhancement and Expansion #276

Introduce a key binding that allows players to pick up nearby items. The player will press the assigned key 'E' when near an item to pick it up. This change improves user interaction and responsiveness in item collection.
 
## **Example (optional)**
- When the player is in contact with an item and presses 'E', the item is picked up.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Map the key 'E' for picking up items
- [x] Add event handling for picking up items when 'E' is pressed
- [x] Modify ItemPickupComponent to handle events when player is in collision with an item and presses 'E'
- [x] Update Documentation
 
**Completion Deadline:** Sep.20
 
# **Documentation**
TBD

# **Member**
- Keagan Stoessel (@keagan-stoessel)
