### ISSUE TITLE
Update MapGenerator to Generate Boss Room, NPC Room, and Gambling Room

### ISSUE THREAD

**Issue by s4693591** [UQcsse3200/2024-studio-1#309]
# **Description**
**Task:** [Update MapGenerator to Generate Boss Room, NPC Room, and Gambling Room].
**Feature:** [Maps]

Update the MapGenerator to generate the rooms of the boss, npc, and gambling within the outlay of the level. This allows Mini-map capabilities where the mini-map can know the location of the rooms on loading the game. This also allow for boss room to be spawned in the furthest room consistently

# **Milestones**
List of steps that need to be completed for this task.
- [ ] Add room type to room creation (Sep 23)
- [ ] Randomly assign npc and gambling room (Sep. 24)
- [ ] Modify furthest room to be boss room (Sep. 24)
- [ ] Refactor to use ToString() for rooms (Sep. 25)
 
**Completion Deadline:** Sep. 25
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Cooper Blackburn (@s4693591)
