### ISSUE TITLE
Update AI Attack Target on Task Change

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#311]
# **Description**
**Task:** Update AI Attack Target on Task Change #311
**Feature:** #257

When an NPC entity switches between tasks its attack target should be updated to reflect the new target from the task. This ensures that the NPC always focuses on the correct target according to its current task, improving combat behavior and responsiveness.
 
## **Example**
AI Target Synchronization: If a new targetable entity is spawned in the game, NPCs will be able to switch tasks and attack the highest priority entity in range.

# **Dependencies**
None

# **Milestones**
- [x] Ensure that when an NPC switches tasks, its attack target is updated to the new task's target. 
- [x] Modify NPC tasks to provide access to their current targets. 
- [x] Update the NPC's attack component to handle target changes during task transitions.
- [x] Test and verify that NPCs update their attack targets correctly when switching tasks.
 
**Completion Deadline:** Sep. 25

# **Documentation**
TBA
 
# **Member**
- Keagan Stoessel (@keagan-stoessel)
- Varun (@vsinh14)
