### ISSUE TITLE
Target Dummy Implementation

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#312]
# **Description**
**Task:** Target Dummy Implementation #312
**Feature:** Item Enhancement and Expansion #276

This task involves implementing a deployable target dummy item. When deployed, enemy NPCs will prioritize attacking the target dummy instead of the player. The target dummy should be designed to distract enemies and provide a tactical advantage to the player in combat scenarios.

# **Dependencies**
- [x] #311
 
# **Milestones**
- [x] Design or source a png asset for target dummy
- [x] Implement the target dummy item, to enable deployment effects
- [x] Develop a deployable item factory to handle items like the target dummy and bear trap
- [x] Add functionality to update the enemy targets in game area so that they pursue the target dummy when deployed
- [ ] Ensure that the target dummy gets disposed when health reaches zero
- [ ] Test and verify that NPCs target the dummy when deployed
 
**Completion Deadline:** Sep. 29
 
# **Documentation**
TBD

# **Member**
- Keagan Stoessel (@keagan-stoessel)
