### ISSUE TITLE
Optimise Maps Basecode to be more testable 

### ISSUE THREAD

**Issue by CameronBadman** [UQcsse3200/2024-studio-1#313]
# **Description**
update the maps base code to be more testable, by severing the inheritance of GameArea and MainGameArea, and create more tests for the maps code components

## SubFeature/component (optional)
- [x] update baseRoom to have to option for NPC Rooms 
- [x] try to update the code to allow for better testing of GameArea (will do next sprint if not done this sprint)

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] update BaseRoom code 
- [x] create a enemy room to allow for a inheritance of Main and BossRoom 
- [x] create a better file organisation
- [x] move uneeded methods in gameArea to Rooms 
- [x] migrate complex methods from GameArea to MainGameArea
- [x] migrate primitive, graphical and asset methods from MainGameArea to GameArea
- [x] split the MainGameArea from the GameArea turning the MainGameArea into GameController 
- [x] use dependancy injection to allowed the GameController to still be able to use GameArea
- [x] #546
- [x] #547
- [x] #548

**Completion Deadline:** 16th October 

# **Documentation**
- [x] https://github.com/UQcsse3200/2024-studio-1/wiki/Room-System 
- [x] https://github.com/UQcsse3200/2024-studio-1/wiki/GameArea-and-GameController

# **Members**
- @CameronBadman 
- @TranHuuPhucAn
