### ISSUE TITLE
Main menu enhancements

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#321]
# Description
Small improvements to the main menu to improve ease-of-use and functionality. Decrease the number of button clicks it takes to do stuff. Hopefully make the menu look a bit nicer.

# Milestones
- [ ] Load option button on main menu (25 Sep)
- [ ] Have mute option accessible directly from the main menu instead of needing to go to the settings screen (26 Sep)
- [ ] Testing (26 Sep)
- [ ] Documentation, sprint form (26 Sep)

**Completion Deadline:** 27 Sep

# Extras (optional)
- [ ] Make main menu ui look amazing
- [ ] Menu button sound effects

# **Documentation**
In progress
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

# **Members**
- Ian Pinto @IanP96
