### ISSUE TITLE
Feather Boss Drop Item Implementation

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#324]
# **Description**
**Task:** Feather Boss Drop Item Implementation #324
**Feature:** Item Enhancement and Expansion #276

Implement a new 'Feather' item, which grants the player a 20% critical hit chance, meaning the player has a 20% chance to deal double damage on attacks. This item is a rare drop from the Birdman boss and can only be acquired after defeating him.

# **Dependencies**
None
 
# **Milestones**
- [ ] Design or acquire a png asset for Feather item
- [ ] Introduce a Feather class that applies the critical hit chance effect to the player upon pickup
- [ ] Implement the functionality for the 20% critical hit chance.
- [ ] Conduct testing
- [ ] Complete documentation
 
**Completion Deadline:** Sep. 29
 
# **Documentation**
TBD

# **Member**
- Keagan Stoessel (@keagan-stoessel)
