### ISSUE TITLE
Inventory Display

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#329]
# **Description**
**Task:** Enhance the UI of Inventory that is displayed(#3).
**Feature:** #269 

Modify the UI of Inventory display so that it is similar to that of minecraft inventory display as instructed by design committee.  This will require changing from the vertical list format to a horizontal list format with only the items and the item count on display. Moreover, update the inventory list with new items added by items team with associated key binding. 
 

# **Dependencies**
- [ ] Items team need to implement new Usable items (#155 )

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Fix the UI of the screen (Sep 19th)
- [ ] Add new items (Sep 29th)
- [ ] Update Documentation (Oct 1)

 
**Completion Deadline:** Oct 2

# **Documentation**
- (Character Inventory Display)[https://github.com/UQcsse3200/2024-studio-1/wiki/Character's-Inventory-Display]
- (Test Plans)[https://github.com/UQcsse3200/2024-studio-1/wiki/Testing-Plan-for-Player's-UI-%E2%80%90-Manual-testing]
 
# **Member**
- Manya @manya-k
