### ISSUE TITLE
Projectile Instantiation

### ISSUE THREAD

**Issue by D-avidTao** [UQcsse3200/2024-studio-1#33]
# **Description**
**Task:** [Projectile Instantiation](#33).
**Feature:** [Projectiles](#12)

Implementing projectile initialisation upon the trigger of an event (from a weapon). This initialisation will require a component and an event listener which signals an event to a projectile factory which will then create and spawn the projectile. 
 
## **Example (optional)**
- **Weapon fires projectile**: A player, holding a projectile weapon will perform some action to indicate that a projectile should be fired, this will send an event signal to the projectile factory which will then spawn a projectile based on any provided parameters and characteristics (like damage, projectile speed, texture and etc).

# **Dependencies**

- [ ] Weapons - Projectile weapons must exist and will be responsible for signalling the projectile to be spawned. (#2)
- [ ] Projectiles - A projectile factory must be implemented. (#35 )

# **Milestones**
- [ ] Define an event listener to listen for the projectile creation event.  (Aug. 20)
- [ ] Call the projectile factory to intialise a projectile. (Aug. 23)
- [ ] Assess code (unit tests and such) (Aug. 25)
 
**Completion Deadline:** Aug. 27
 
# **Documentation**
TBD
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- David (@D-avidTao) (david)
