### ISSUE TITLE
Decouple weapon from player

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#331]
# **Description**
**Task:** [Decouple weapon from player](#331).
**Feature:** [ Weapon and Projectiles 2](#118)

Now the player can directly use a weapon from the MeleeWeapon/RangedWeapon class instead of relying on the WeaponComponent class.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Change pickup and drop method to handle weapon entity (Sep. 27)
- [x] Add firing controller for weapon entity (Sep. 27)
- [x] Create tests for weapon entity (Sep. 27)
- [ ] Add documentation (Sep. 28)
 
**Completion Deadline:** Sep. 28
 
# **Documentation**
TBD
 
# **Member**
- Trong Hieu Mai (@Magnius001)
