### ISSUE TITLE
Load Shop Room (NPC Room)

### ISSUE THREAD

**Issue by s4693591** [UQcsse3200/2024-studio-1#334]
# **Description**
**Task:** Load NPC Room

With the map generation now complete. There is the task of creating an NPC room to spawn in the seed-determined position that uses the tokens gathered to spend those on buying items. This room will have multiple different buyable items that will be created by @Jas2310 for conditional purhcasing

# **Dependencies**
This task is dependent on Coin system implementation, and will collaborate synchronously with items team
- [x] Coin Depedency 

# **Collaborations**
This task is collaborating directly with @Jas2310 to create buyable items that will make the spawning of the NPC much simpler
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Spawn NPC room in level generation (Sep 27)
- [x] Create Buyable Items (Sep 27)
- [x] Merge Buyable Items Code (Sep 28)
- [x] Implement Buyable Items spawning in room (Sep 29)
Room esting could not be completed with the limited mock game area sources available
Buyable item testing was completed by @Jas2310 
 
**Completion Deadline:** Sep 31

# **Documentation**
- [Main description of feature](../wiki/NPC Room)
 
# **Member**
- Cooper Blackburn @s4693591 
- Jasmine Hong @Jas2310
