### ISSUE TITLE
Creation of reroll item

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#335]
# **Description**
**Task:** [Creation of reroll item](#3).
**Feature:** [Item enhancement and expansion] #276 

Creation of a reroll item that allows the player the chance to obtain a new item which may be better/worse than the original. The reroll item should be a UsableItem that gets added to the inventory. It can only be used when in collision with the other item that the player wants to "reroll". 
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Creation of a new "Reroll" item class, that extends from UsableItem (Sep 22.)
- [ ] Add key bindings to handle when a "Reroll" item is used (Sep 23.)
- [ ] Add new method to handle the "Reroll" item effect (Sep 25.)
- [ ] Creation of "Reroll" item asset (Sep 27.)
 
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Jasmine Hong (@Jas2310)
