### ISSUE TITLE
Big Red Button

### ISSUE THREAD

**Issue by notinclined** [UQcsse3200/2024-studio-1#336]
# **Description**
**Task:** Big Red Button #336
**Feature:** Item Enhancement and Expansion #276 

This is a task that implements a usable item that eliminates all enemies in the current room.

# **Dependencies**

- [ ] #313
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design image for item 
- [ ] Implement the functionality of the item to kill all animals in the current room 
- [ ] Ensure that the item only works in the current room 
- [ ] Create testing for the item 
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- TBD
 
# **Member**
- Liam Morris (@notinclined)
