### ISSUE TITLE
Boss teleporter

### ISSUE THREAD

**Issue by notinclined** [UQcsse3200/2024-studio-1#337]
# **Description**
**Task:** Teleporter item #337
**Feature:** Item Enhancement and Expansion #276 

This is a task that implements a usable item that allow the player to teleport to the boss room bypassing all additional battles 

# **Dependencies**

- [ ] #313
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Design image for item 
- [ ] Implement the functionality of the item to teleport to boss room
- [ ] Ensure that the item only teleports to each of the respective bosses on each floor
- [ ] Create testing for the item 
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
- TBD
 
# **Member**
- Liam Morris (@notinclined)
