### ISSUE TITLE
Collisions 

### ISSUE THREAD

**Issue by brose7561** [UQcsse3200/2024-studio-1#34]
Task: Collisions (#34)
Feature: Projectiles (#12)

Implement collision events. When a projectile intersects with an entity on the same physics plane a collision event will be triggered on that entity. The collision will inform the hit entity of the projectile's payload. If the entity is listening it may choose to update based on this payload. After a collision the projectile is removed.     

# **Dependencies**

- Animal  (#10)  
- Character (#3) 
- Map (#9) 
- Projectile Instantiation (#33)
- Create and define projectile Factory (#35 )

- [ ]  Animals will collide with a projectile. 
- [ ] Character will collide with a projectile.
- [ ] walls and map features will collide with a projectile.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] define a collision event containing damage information (Aug. 19)
- [ ] define a event listener to listen for projectile intersecting with an entity (Aug. 20)
- [ ] write test, verify function (Aug. 23) 
- [ ] update wiki and documentation (Aug. 24)

 
**Completion Deadline:** Aug. 24

 
# **Documentation**
- TBD
 
# **Member**

- Benjamin (@brose7561) (Ben)
