### ISSUE TITLE
Werewolf Fang (Boss drop)

### ISSUE THREAD

**Issue by Div1o1** [UQcsse3200/2024-studio-1#347]
# **Description**
**Task:** Werewolf Fang (Boss drop)
**Feature:** Item Enhancement and Expansion

Introduce 'Werewolf Fang' that causes bleed damage on enemies. This bleed effect drains the health of foes gradually, forcing them to suffer continuous damage even after the initial strike. The item works with weapons that cause a bleed effect, such as a knife.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Design and create pixel PNG asset for the Bleed item.
- [x] Implement the code for the bleed item, add functionality of the item.
- [x] Unit testing for the item created.

**Completion Deadline:** Sep. 29

 
# **Documentation**
TBD
 
# **Member**
- Keagan Stoessel (@keagan-stoessel)
- Divyanshu (@Div1o1 )
