### ISSUE TITLE
Creation of new items - Heart and Bear trap

### ISSUE THREAD

**Issue by Parasverma17** [UQcsse3200/2024-studio-1#348]
# **Description**
**Task:** [Creation of new items - Heart and Bear trap](#348).
**Feature:** [Item enhancement and expansion](#276 )

Creation of new items like Heart and Bear trap. Heart item increases the maximum health of the player giving an extra edge to health management. Bear trap item can be deployed by the player and upon collision with the enemy entity it does damage to that. It provides with new defensive strategies.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Creation of "bear trap" item class that extends Usable item (Sep. 26)
- [x] Creation of Trap component that manages the trap implementations (Sep. 26)
- [x] Creation of Heart item class that extends Buff item and add setmaxHealth() in CombatstatsComponent (Sep. 28)
- [x] Added assets for heart and bear trap (Sep. 28)
- [x] Add maxHealth in Bandage and medkit and update their tests (Sep. 29)
- [x] Tests for Heart and Bear trap (Sep. 30)

**Completion Deadline:** Sep. 30

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Paras Verma (@Parasverma17 )
