### ISSUE TITLE
Create and Define Projectile Factory

### ISSUE THREAD

**Issue by yashwanthg22** [UQcsse3200/2024-studio-1#35]
# **Description**
**Task:** [Create and Define Projectile Factory](#35) 
**Feature:** [Projectiles](#12)

Implement a Projectile Factory that will be responsible for creating projectiles in the game. This factory will allow the creation of projectiles with specific attributes such as texture, speed, direction, damage payload, and animation/movement components.The task includes defining the behavior and lifecycle of a projectile.

## **Example (optional)**
- **Creation**: This class will oversee the initialisation and creation of projectiles with certain characteristics as signaled by a projectile creation event. Say for example you wanted a fireball, you would have to signal the event providing the desired texture, damage, projectile speed and so on and this class will create a projectile reflecting these characteristics.

# **Dependencies**
- [ ] Projectile Instantiation(#33) - It tells the projectile factory what components to add and create.

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Creating Projectile Factory class to manage the creation of projectiles.  (Aug. 19)
- [ ] Define methods for setting projectile attributes including texture, speed, direction, and damage payload. (Aug. 21)
- [ ] Add and integrate a listening component to detect collisions between projectiles and entities. (Aug. 23)
- [ ] Conduct unit tests to ensure all components of the projectile factory operate as expected and Perform a code review to ensure quality. (Aug. 25)
 
**Completion Deadline:** Aug. 27
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- e.g. Yashwanth Raj (@yashwanthg22) (Yashwanth)

**Comment by brose7561** [comment]
completed at same time at #33 and #34
