### ISSUE TITLE
Animal Animations 

### ISSUE THREAD

**Issue by vsinh14** [UQcsse3200/2024-studio-1#36]
# **Animal Animations**
**Task:** [Implement animal animations](#3).
**Feature:** [Animal Behavior and Attributes ](#2)

This task will be implementing basic animations (movement and attack) for the animals (NPC) to their factory. 
This will require adding additional animations to the components for NPC GhostAnimationController.java. 

Once implemented, the NPC moving around will have a walking animation, and once the PC (player character) is in range, they shall enact their attack animation in the direction of the player (dependent on the animal's attack type). 
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Attacks being implemented #32 
- [ ] Movement patterns being implemented (#39)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Get movement animations working (Aug. 17)
- [ ] Attack animations  (Aug. 18)
- [ ] Merge with dependencies (Aug. 19)
 
**Completion Deadline:** Aug. 20

# **Documentation**
NA
 
# **Member**
- Varun Sinha  (vsinh14) (liltawe)
