### ISSUE TITLE
Collaboration for Player and Maps Saving/Loading

### ISSUE THREAD

**Issue by TriNhan-Pham** [UQcsse3200/2024-studio-1#377]
# **Description**
**Task:** [Collaboration of Team 1, 5, 6 for saving/loading maps and player].

Discussions on how to save the rooms and player statistics. The saved version of the game is stored under a JSON file and can be loaded from map components. This collaboration may be progressive throughout current and upcoming sprints to always up-to-date with changes of the game.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Finish saving into JSON for maps (Sep. 24)
- [x] Finish saving into JSON for player (Sep. 22)
- [x] Finish loading for maps (Sep. 26)
- [x] Finish loading for player (Sep. 26)
- [x] Finish debugging (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
TBD
 
# **Member**
- Tri Nhan Pham (@TriNhan-Pham)
- Manya (@manya-k)
- Dhruv Anil (@dhruvanil55)
