### ISSUE TITLE
Create different game over screens

### ISSUE THREAD

**Issue by TriNhan-Pham** [UQcsse3200/2024-studio-1#378]
# **Description**
**Task:** [Create different game over screens].

This task aims to enhance the game over screen which was inspired by Cupcake. Specifically, the animal that hit the character last will have a separate game over screen that that animal taunts player.
 
## **Example (optional)**
- If your character died because of a dog attack, then the dog would appear on the game over screen and say something to taunt you.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Have a discussion with team 7 on how to get the last attact animal (Sep. 23)
- [x] Finish getting the last attack animal's name (Aug. 24)
- [x] Finish creating different game over screens (Sep. 30)
 
**Completion Deadline:** Sep. 30
 
# **Documentation**
TBD

# **Member**
- Tri Nhan Pham (@TriNhan-Pham)
