### ISSUE TITLE
Ring Of Fire

### ISSUE THREAD

**Issue by notinclined** [UQcsse3200/2024-studio-1#388]
# **Description**
**Task:** Ring Of Fire
**Feature:** Item Enhancement and Expansion #276 

This is a task that implements a buff item that creates a ring that damages all enemies that make contact with it.

# **Dependencies**

- [x] #267 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design image for item 
- [x] Implement the functionality of the item to spawn and follow the player
- [x] Create testing for the item 
 
**Completion Deadline:** Oct. 1
 
# **Documentation**
- TBD
 
# **Member**
- Liam Morris (@notinclined)
