### ISSUE TITLE
Tombstone

### ISSUE THREAD

**Issue by notinclined** [UQcsse3200/2024-studio-1#389]
# **Description**
**Task:** Tombstone
**Feature:** Item Enhancement and Expansion #276 

This is a task that implements an item that spawns a friendly pet to attack opposing enemies.

# **Dependencies**

- [x] #267 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design image for item 
- [x] Implement the functionality of the item to spawn pet and follow the player
- [x] Create testing for the item 
 
**Completion Deadline:** Oct. 1
 
# **Documentation**
- TBD
 
# **Member**
- Liam Morris (@notinclined)
- Varun (@vsinh14  )
