### ISSUE TITLE
Animal/NPC Movement

### ISSUE THREAD

**Issue by mblauberg** [UQcsse3200/2024-studio-1#39]
# **Description**
**Task:** Animal/NPC Movement (#3).
**Feature:** Animal Behaviour and Attributes (#2)

Implement all basic animal movements for rats, gorillas, dogs and crocodiles. This will require modifying 'WanderTask' and 'ChaseTask' to be able to fit the desired animal behaviours. The 'MovementTask' class, will need a new constructor that takes a velocity parameter, so that the other tasks can call to set a custom speed. This will call the 'PhysicsMovementComponent' to update the speed of that particular entity. Each particular animal will need a creation method within the 'NPCFactory' class which creates a new 'AITaskComponent' adding both 'WanderTask' and 'ChaseTask' to them. The 'ChaseTask' may need to be extended by a new task class to be able to fully implement a certain animal's movement behaviour. New tasks such as a 'HowlTask' or 'RunAwayTask' may need to be created for dogs and rats respectfully.

# **Dependencies**

- [x] #36 
- [x] Spawning mechanism is needed in order to use the animals within the maps

# **Milestones**
List of steps that need to be completed for this task.
- [x] Modify 'ChaseTask' and 'WaitTask' (Aug. 17)
- [x] Implement variable movement speed (Aug. 18)
- [x] Make methods to create animals within 'NPCFactory' (Aug. 19)
- [x] Document on the wiki (Aug. 20)
 
**Completion Deadline:** Aug. 20
 
# **Documentation**
- [Animal Movement](../wiki/Animals/Movement)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Michael Blauberg (GitHub mblauberg)
