### ISSUE TITLE
Refactor Boss AI to use Priority-Based Task System

### ISSUE THREAD

**Issue by mblauberg** [UQcsse3200/2024-studio-1#391]
# **Description**
**Task:** [Refactor Boss AI to use Priority-Based Task System](#).
**Feature:** [Animals: Improved AI, New Attack Types, and NPCs Interactions](#257)

This task involves refactoring the BossAIComponent to use the regular AITaskComponent utilized by other NPCs, replacing the existing state machine with a priority-based task system. Each state in the original BossAIComponent is converted into a separate task, such as `JumpTask`, `RangeAttackTask`, and `AOEAttackTask`. Attack components are disabled by default and are enabled within their corresponding tasks. Existing tasks like `ChargeTask`, `ChaseTask`, and `RunAwayTask` are modified to have dynamic priorities and accept parameters to integrate seamlessly with the priority system. Tasks are enhanced to handle more complex behaviours, including cooldowns and improved priority management, resulting in smoother task execution and more dynamic NPC movements for all entities.
 
# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] `JumpTask` being implemented (#xx)
- [ ] `AOEAttackComponent` being implemented (#268)
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Create active and inactive non-conflicting priorities for all tasks.
- [ ] Update `ChargeTask` and `RunAwayTask` to perform a single movement before stopping.
- [ ] Update `ChargeTask`, `JumpTask` and `RunAwayTask` to have dynamic priorities and cooldowns.
- [ ] Integrate updated tasks into the bosses, updating the configs as needed, changing the AI component to use `AITaskComponent`.
- [ ] Create a `AOEAttackTask` to handle the `AOE_ATTACK` state from the `BossAIComponent`.
- [ ] Create a `RangeAttackTask` that is able to use the two different types of shooting.
- [ ] Test all tasks work together well and update the bosses' configs as needed.
- [ ] Update documentation and JavaDocs.
 
**Completion Deadline:** Oct. 2

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
 
# **Member**
- Michael Blauberg (@mblauberg)
