### ISSUE TITLE
Creation of Divine Potion item

### ISSUE THREAD

**Issue by Parasverma17** [UQcsse3200/2024-studio-1#393]
# **Description**
**Task:** [Collaboration of Team 2,3 to create divine potion](#3).

Creation of divine potion item class which extends Buff item and does increase health and speed of the player upon pickup.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create divine potion class that extends buff item (Sep. 29)
- [x] Create its asset (Sep. 29)
- [x] Add functionality for Health boost (Sep. 29)
- [x] Add functionality for speed boost (Sep. 29)
- [x] Tests for divine potion (Oct. 1)
 
**Completion Deadline:** Oct. 1
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Paras Verma (@Parasverma17 ) 
- Divyansh Agarwal (@divyanshddn146)
