### ISSUE TITLE
Collaboration ticket for fixing saving and loading - Dhruv, Manya and Varun

### ISSUE THREAD

**Issue by dhruvanil55** [UQcsse3200/2024-studio-1#406]
# **Description**
**Game Saving Loading Functionality:** [Load and Save](#3).

This fixes the saving and loading functionality for both player and maps team, by fixing some bugs and making the code quality better so that the loading and saving system is more understandable. Furthermore major fixes will be made to the load button implementation in the menu and the functionality of the load button to make the code cleaner.
 
## **Example (optional)**
- **Load Button Functionality**: Load button won't exist when save files don't exist, and when clicked will lead to directly starting the game instead of going through the player select screen as it will get the data from the previously saved files.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Cleaning up map saving loading feature to work off of configs and only saving 1 json file for map data.(Oct. 3)
- [x] Cleaning up the load button functionality so that it acts as a button on the screen and leads directly into the game(Oct. 4)
- [x] Player loading functionality changes  to save the pets(Oct. 4)
- [ ] Documentation changes (Oct. 5)
 
**Completion Deadline:** Oct. 4

# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Dhruv Anil (@dhruvanil55)
- Varun Sinha (@vsinh14)
- Manya Khosla (@manya-k)
