### ISSUE TITLE
Refine Character Animation

### ISSUE THREAD

**Issue by nadiadmello** [UQcsse3200/2024-studio-1#407]
# **Fix Character Scaling and Direction**
**Task:** [Animation](#410)
**Feature:** [Character](#410)

Currently, the assets for the new players have had to be scaled up within the code base, causing off-centre rendering of the character. Additionally, these characters only have one direction of walk, which causes it to walk backwards when moving left.  These fixes will require modifying the assets of the human/homeless players. The methods within the 'LoadPlayer' will also require modification after making these changes. To fix the centring issues, the AnimationRenderComponent may need to be adjusted.

## **Example**
Ensuring the character is cantered within the region it is rendered in.
When the walk-left trigger is sent, the character should face the direction as it is currently facing backwards.

# **Dependencies**
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the required character assets (Oct. 8)
- [x] Add any required animations/name changes in 'LoadPlayer' (Oct. 8)
- [x] Implement any refinements to the LoadPlayer class (Oct. 10)
- [x] Implement any scaling refinements to the AnimationRenderComponent class (Oct. 10)
- [x] Update PlayerAnimationController class to deal with directional animations (Oct. 10)
- [x] Clean up any code (Oct. 10)
- [ ] Testing (Oct. 11)
- [ ] Documentation on the wiki (Oct. 11)
 
**Completion Deadline:** Oct. 11.
 
# **Documentation**
- [Character Animation](https://github.com/UQcsse3200/2024-studio-1/wiki/Character-Animations)
 
# **Member**
- Nadia D'Mello (@nadiadmello)
