### ISSUE TITLE
Character Clean Up

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#410]
# **Description**
This ticket is responsible for various small tasks that will help in delivering the final game. These include:

### 1. Refactors the code and enhance the readability of all classes related to player
  - Refactor Player Animation component/ PlayerSelection.java
  - Refactor Player Factory

### 2. Fix Animations for non-default players:
   - Modify the code so that left and right walk animations are properly displayed
   - Refine the scaling and centring of the character
   - Add final touches to the animations, including directional movement for animations other than walking
  
### 3.  Enhance the UI of Inventory:
  - Change the size of box so that it does not overlap with the map
  
### 4. Change the sound effects: 
  - Change the sounds of player getting hit
  - Modify the code so that the sounds work in all rooms

### 5. Save pets and buffs:
  - Add saving mechanism for all new components implemented in sprint 3
  
### 6. Add statistics on end game screen
  - Display the state of player on the end screen
  
### 8. Fix loading health bar
  - Modify the code so that when the game is loaded again the player health bar reflects the health properly

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Refactor Player Animation component (Oct 12th)
- [x] Refactor Player Factory (Oct 10th)
- [x] Fix Animations for non-default players (Oct 19th)
- [x] Change the sound effects (Oct 19th)
- [x] Save pets and buffs (Oct 5th)
- [x] Add the ability to shoot diagonally (oct 19th)
- [x] Fix loading health bar (Oct 19th)
- [x] #446
- [x] Update/enhance the documentation for all
- [x] Conduct testing for anything new added or previous test plans

**Completion Deadline:** OCT 21

# **Documentation**
TBA

# **Members**
- @manya-k 
- @nadiadmello 
- @Jordamnmn 
- @VuKhanhVyHo 
- @SIN-Willett

**Comment by iishiishii** [comment]
Is there any dependency on other tickets? Otherwise, this ticket is approved and you can start working on the task tickets.

**Comment by SIN-Willett** [comment]
This has all been completed
