### ISSUE TITLE
Balancing damage. 

### ISSUE THREAD

**Issue by brose7561** [UQcsse3200/2024-studio-1#412]
**Task:** [Balancing damage]
**Feature:** [weapons]

The current implementation, the projectiles are super powerful and quite large compared to the health and size of the animals. the player can kill most animals with one shot. This task is all about making the game enjoyable and will scaled. Propose several default and custom damages and then get some feedback on the games usability. 
 
# **Dependencies**

this may depend both on the default projectile implementation. Specific projectile use cases, like the shotgun effect also potentially changes to the config that the projectile is spawned with in weapon component. 

- [ ] weapons
- [ ] projectiles
 
# **Milestones** - all on Oct 7
- [x] Implement some damage and scaling changes
- [x] test the changes for usability across a variety of use cases
- [ ]  collaboratively test with some members of main impacted team, weapons, animals, player
- [ ] push and merge reviewed by members of balancing team
 
**Completion Deadline:** Oct 8 

 
# **Documentation**
- https://github.com/UQcsse3200/2024-studio-1/wiki/Projectile
 
# **Member**
- Name (GitHub Username) (Slack Handle)
- Brose7561 ben
