### ISSUE TITLE
Projectile Range

### ISSUE THREAD

**Issue by brose7561** [UQcsse3200/2024-studio-1#414]
# **Description**
**Task:** Projectile Range
**Feature:** projectiles and weapons

the projectile range is infinite at the moment. The shotgun projectile in particular is meant to be unique in its high damage but over a very close range. This task is about ching the range the projectile has traveled and making sure that it is within a predefined distance in the stats object.

## **Example (optional)**
A shotgun should not be able to shoot an animal on the other side of the map. 

# **Milestones**
List of steps that need to be completed for this task.
- [x]  Update the projectile config with a default range
- [x] Update the projectile config called in the weapon shotgun class with a specified range.
- [x]  Make a check on the projectile that disposes if range is crossed
- [ ]  two unit test one checks that a player in range is hit, next one changes range and check the entity is now not hit. 
- [ ] merge, review, PR 
 
**Completion Deadline:** Oct 10 

 
# **Member**
- Benjamin Rose, brose7561, ben
