### ISSUE TITLE
Polishing items and improving builds

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#416]
# **Description**
This feature ticket focusses on making final, minor adjustments to features previously implemented, and completing unfinished items that were started on from last sprint, that are missing major functionality. Another task of this feature ticket includes improving the build methods, in particular, the item factory. The item factory should create items that are unique to the character chosen (eg. the tombstone item should only show for the necromancer character).

## SubFeature/component

1. Minor adjustments to features previously implemented, which includes...
- Damage buff item: Fixing the UI progress bar, which currently does not increase by the correct amount
- Energy drink item: Fixing the UI progress bar, which currently does not load to the player's current speed after saving
- Hear item: Change max health cap to 250
- Target dummy: Change priority task to the actual target dummy
- Armor item: Implement UI progress bar
- Beartrap item: Add feature so that beartrap immobilizes the enemies for a set time duration and does not gets triggered for the Pets. 

2. Finishing items started on from last sprint such as...
-  Ring of fire item
- Gambling item
- Bleed item
- Bossroom teleport item

3. Improving builds, in particular, the item factory. 

# **Dependencies**
TBD

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] Fixing the damage buff UI progress bar (Oct. 14)
- [x] #507  (Oct. 14)
- [x] Changing the max health to 250 for the heart item (Oct. 14)
- [x] Implementing immobilizing feature for beartrap (Oct. 14)
- [x] To Make Beartrap not trigger for the pets (Oct. 14)
- [x] #522 (Oct. 14)
- [x] #523 (Oct. 14)
- [x] #544 (Oct. 14)
- [x] #519 (Oct. 14)
- [x] #347 (Oct. 14)
- [x] #508 (Oct. 14)
- [x] Testing (Oct. 15)
- [x] Documentation (Oct. 16)

**Completion Deadline:** Oct. 16

# **Documentation**
TBD

# **Members**

- Keagan Stoessel (@keagan-stoessel)
- Paras Verma (@Parasverma17 
- Jasmine Hong (@Jas2310)
- Divyanshu (@Div1o1)
- Liam Morris (@notinclined)

**Comment by The-AhmadAA** [comment]
Add labels and select the Project stage for this, otherwise it looks good :)
