### ISSUE TITLE
Refactor Effects System and Implement Animated Overlays

### ISSUE THREAD

**Issue by mblauberg** [UQcsse3200/2024-studio-1#427]
# **Description**
**Task:** [Refactor Effects System and Implement Animated Overlays](#3).

This task involved decoupling effects from attack components by introducing a separate `EffectComponent`. Effects are now applied through the `EffectComponent` instead of directly within attack components. Additionally, `EffectConfig` has been separated from `AttackConfig` into its own file, and all effects have been moved to a dedicated package outside of the attack package. The `PoisonEffect` and `StunEffect` have been properly implemented, and animated overlay entities have been created for both effects to visually represent them on the affected targets.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Decoupled effects from attack components into a separate `EffectComponent` (Oct. 6)
- [x] Allowed handling of applying effects via `EffectComponent` instead of within attack components (Oct. 6)
- [x] Split `EffectConfig` from `AttackConfig` into its own file (Oct. 7)
- [x] Moved effects into a package outside of the attack package (Oct. 7)
- [x] Implemented `PoisonEffect` and `StunEffect` properly (Oct. 8)
- [x] Created working animated overlay entities for `PoisonEffect` and `StunEffect` for affected targets (Oct. 10)
- [x] Integrate relevant effects to existing NPC's (Oct. 10)
- [x] Documented changes (Oct. 11)
 
# **Documentation**
- [Animal Attack System](https://github.com/UQcsse3200/2024-studio-1/wiki/Animal-Attack-System)
- [JavaDoc for Effect Components](JavaDoc/com/csse3200/game/components/effects)
 
# **Member**
- Michael Blauberg (@mblauberg)
