### ISSUE TITLE
Loading Map Tiles with Graphics

### ISSUE THREAD

**Issue by s4693591** [UQcsse3200/2024-studio-1#43]
# **Description:** 
**Task:** Loading Map Tiles with Graphics
**Feature:** Maps - Team 6 #9

Implement functionality of loading in map assets into a grid. In this task the first map will be hard coded, but a terrain factory will also be implemented to take the output of json files into graphical map with boundaries and doors
Doors will be treated as walls for now until transition functionality is set, but will be loaded in as door tiles.
 
# **Dependencies**
- [ ] Dependency 1 (#xx) Character Movement
- [ ] Dependency 2 (#xx) Converting Seed Randomised Json File into Tile Data

e.g.
- [ ] Character movement and how the entity interacts while moving is needed to know to know how to create map boundaries
- [ ] Tile data needs to be known for input of seed random maps, instead of hard coding the map layouts
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Get image assets to display (Aug. 19)
- [ ] Have map layout with images assets as a grid (Aug. 20)
- [ ] Map boundaries in effect (Aug. 23)
- [ ] Map can be loaded in with boundaries in effect (Aug. 23)
 
**Completion Deadline: Without Tests** Aug. 23
**Completion Deadline: With Tests** Aug. 27
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens/Terrain)
