### ISSUE TITLE
Refractor RangeAttackComponent and add animations for Final Boss range attacks

### ISSUE THREAD

**Issue by justarandomnameduh** [UQcsse3200/2024-studio-1#430]
# **Description**
**Feature Ticket**: [Improve Boss Mechanics with BulletStorm Feature and New Final Boss](#439)
**Task:**: Refractor and extend RangeAttackComponent for Final Boss

This task involve changing `RangeAttackComponent` for easy-to-invoke function with customizable parameters, either being loaded from JSON files or edited directly from the animals. As the final boss' range attacks require variation in attack patterns, `RangeAttackComponent` should consider different projectile spawning and moving mechanism, including fixed location spawning, spiral movement, etc. making the final worthy of it being the last challenge of the game.
The projectile should also have a limited range (disappear after traveling a given distance instead of only disappearing only hitting the wall).
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Refractor ProjectileFactory for limited range (Oct. 8)
- [x] Refractor RangeAttackComponent, preparing for new changes (Oct. 9)
- [x] Add new shooting mechanism in RangeAttackComponent (Oct. 10)
- [x] Complete documentation and testing (Oct. 12)
 
**Completion Deadline:** Oct. 12
 
# **Documentation**
- TBD
 
# **Member**
- Quang Minh Tien Nguyen (@justarandomnameduh)
