### ISSUE TITLE
Shop Room Saving and Fix

### ISSUE THREAD

**Issue by dhruvanil55** [UQcsse3200/2024-studio-1#434]
# **Description**
**Task:** Saving Shop Rooms.
**Feature:** Map Saving Loading

Working on Fixing Shop room code to not randomise the positions of the items in the room, as well as save the items in the shop rooms in the current instance of the game that the player is playing as a part of the Map Save JSON so that when the game is reloaded the items in the shop rooms are the same as they were when the player saved the game. 

## **Example (optional)**
- **Save**: When players save the game the items that were bought in the shop room won't exist again anymore when they load the game.

# **Milestones**
List of steps that need to be completed for this task.
- [x] Step 1: Make Shop Room key binding so that we can go to shop room instantly for testing(Oct. 10)
- [x] Step 2: optimise shop room code so that items only spawn linearly. (Oct. 10)
- [x] Step 3: Implement shop rooms items saving. (Oct. 10)
 
**Completion Deadline:**  
- [x] October 11. Everything will be implemented and in a pull request by October 11. Manual testing in saving and loading will cover manual testing for this.
 
# **Documentation**
- [Map Saving Loading](https://github.com/UQcsse3200/2024-studio-1/wiki/Map-Saving-and-Loading)
 
# **Member**
- Dhruv Anil (@dhruvanil55)
