### ISSUE TITLE
New music

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#436]
# **Description**
Change the music system to introduce new music and allow for new music in the future.
- Replace the OG box boy background music with my epic 8-bit music
- Refactor music playing to accept a music type (normal, boss), making it easier to switch between music types mid-game without having to keep track of asset paths.

# **Dependencies**
- Maps team will likely be adding boss music, I will try to design the code so they only have to change one string for the asset path.

# **Milestones**
- [x] Create and add the new default music to the repo (10 Oct)
- [x] Add code for music switching (11 Oct)
- [ ] Manual testing (11 Oct)
- [ ] PR (11 Oct)
- [ ] Documentation, sprint form (11 Oct)

**Completion Deadline:** 12 Oct

# **Extras (optional)**
- Even more music e.g. menu music? Death screen music?

# **Documentation**
In progress
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)
- ...

# **Members**
Ian Pinto @IanP96

**Comment by IanP96** [comment]
There was a change of plans, death screen music has been added and is now in main.
