### ISSUE TITLE
Character Animation

### ISSUE THREAD

**Issue by nadiadmello** [UQcsse3200/2024-studio-1#44]
# **Character Animation**
**Task:** [Animation](#3).
**Feature:** [Character](#3)

Implement the character animation. Different animation frames will be displayed based on the character's moving status. This will require creating a new class 'PlayerAnimationController' which extends from 'Component' and use an event listener to update the animation based on the character's status (stationary or moving). A method will also need to be added within the 'PlayerFactory' to register all the required animation frames to the AnimationRenderComponent.
 
## **Example**
- **Standing**: While the character is stationary, aka no user input, the animation will display the default character animation.
- **Walking left**: While the character moves left, the character animation will change to the walk left.

# **Dependencies**
- [ ] Character movement
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Plan out the different frames based on the created pixel art (Aug. 19)
- [x] Implement the 'PlayerAnimationController' and display the character while stationary. (Aug. 20)
- [x] Change to walking frames once the character is moving (Aug. 22)
- [ ] Testing (Aug. 23)
- [ ] Documentation on the wiki (Aug. 23)
 
**Completion Deadline:** Aug. 23
 
# **Documentation**
- [Character Animation](../wiki/Player/Animation) 
 
# **Member**
- Nadia D'Mello (@nadiadmello)
