### ISSUE TITLE
Enhance Coins Component

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#446]
# **Description**
**Task:** Add text and sound effects for when coins are collected
**Feature:** #410 

Add sound effects for when player collects coins, for futher enhancement. Moreover,  to make the game more interactive, inform player how much coins they collect by defeating each animal.
 
## **Example (optional)**
When player successfully defeats an animal, a text is displayed on the screen to inform player how many coins they earned along with some sound effects

# **Dependencies**
- [x] #296 (#xx)

# **Milestones**
List of steps that need to be completed for this task.
- [x] enhance the current implementation (Oct 12th)
- [x] add the text to UI (Oct 12th)
- [x] Add sound effects (October 12th)
- [x] Add tests if needed (October 14th)
- [x] Documentation (Oct 14th)
 
**Completion Deadline:** Oct 16th

 
# **Documentation**
- [Scoring System](https://github.com/UQcsse3200/2024-studio-1/wiki/Scoring-System)
 
# **Member**
- Manya Khosla @manya-k
