### ISSUE TITLE
Saving Character's State 

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#45]
# **Description**
**Task:** saving character's present state(#3).
**Feature:** #3 

Save the player's character state, including health, weapons, items, and their positions. This information will be displayed on GUI during the game, showing all currently held items and weapons.

## **Example **
- A player's heath percentage, items, weapons and their current position will always be displayed on the screen  and as soon as the player decides to save the game, all of these things will be saved in a json file to be used later.

# **Dependencies**
- [ ] #6 
- [ ] #2 

e.g.
- [ ] Items need to be created for them to be saved and displayed.
- [ ] Weapons need to be created for them to be saved and displayed.
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Display character's current inventory on GUI (21st Aug)
- [ ] Save character's inventory in a json file (25th Aug)
- [ ] Test all components (27th Aug)
- [ ] Documentation (27th Aug)

**Completion Deadline:** Aug. 28

# **Documentation**
- TBA
 
# **Member**
- @manya-k
