### ISSUE TITLE
Animals-scaling

### ISSUE THREAD

**Issue by vsinh14** [UQcsse3200/2024-studio-1#454]
# **Description**
**Task:** [Animals Scaling]().
This task was to implement animal sprite scaling + density scaling (bosses should not be easily moveable). 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Add scaling code into factories and configs (Oct 8)
- [x] Add scaling parameters to configs (Oct 10)
- [x] Add density code to factories (Oct 11)
- [x] Add density parameters to configs (Oct 12)
- [x] Add above to pets (Oct 12)
 
**Completion Deadline:** Oct 12

# **Documentation**
 
# **Member**
- Varun sinha @vsinh14
