### ISSUE TITLE
UI REFACTOR

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#457]
# **Description**
**Task:** Refactor and clean up UI
**Feature:** #410 

Upon the request of design committee, the current implementation of inventory display is enhanced and refactored so that when new items are introduced to the game, they are not required to update in many places. Moreover, refactor so that the item are displayed only when they are collected. 
 
## **Example (optional)**
when a new game is started the bottom inventory bar is empty and as we collect more `usable items` they are added and displayed on the screen.

# **Dependencies**
- [x] Player Factory needs to be refactored #424 

# **Milestones**
List of steps that need to be completed for this task.
- [x] Refactor Key binding (Oct 10th)
- [x] Refactor the display (Oct 11th)
- [x] Testing (Oct 13th)
- [x] Update Documentation (Oct 14th)

 
**Completion Deadline:** OCT 16th

# **Documentation**
- [Main description of feature](https://github.com/UQcsse3200/2024-studio-1/wiki/Character's-Inventory-Display)
 
# **Member**
- Manya @manya-k
