### ISSUE TITLE
Create specific weapons location tracking for different host entities

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#459]
# **Description**
**Task:** [Create specific weapons location tracking for different host entities](#459).
**Feature:** [Polishing weapons](#415)

Different users of the weapons will have different scale and hand position. This task aim to address that by setting a specific offset for the weapon entity for each users.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Determine offsets (Oct. 13)
- [ ] Implement offsets (Oct. 13)
- [ ] Test (Oct. 14)
- [ ] Revise documentation (Oct. 14)
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
TBD
 
# **Member**
- Trong Hieu Mai (@Magnius001 )
- Thang Hoang Cao Quoc (@thanghoang7020202 )
