### ISSUE TITLE
Improve weapon scaling

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#460]
# **Description**
**Task:** [Create specific weapons location tracking for different host entities](#459).
**Feature:** [Polishing weapons](#415)

Improve the size of the weapon and its corresponding animations.

# **Dependencies**
None
 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Enlarge slashing effects for melee weapons (Oct. 13)
- [ ] Revise ranged weapon size (Oct. 13)
- [ ] Test (Oct. 14)
- [ ] Revise documentation (Oct. 14)
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
TBD
 
# **Member**
- Trong Hieu Mai (@Magnius001 )
- Thang Hoang Cao Quoc (@thanghoang7020202 )
