### ISSUE TITLE
Creation of an Armoury Room to test items and weapons

### ISSUE THREAD

**Issue by notinclined** [UQcsse3200/2024-studio-1#464]
# **Description**
The Armory room is a testing feature that will be included in both the test option and the actual game. It will function similarly to a developer room, spawning all items and weapons within a singular room to be tested. 

## **Examples**
- **Part/Feature**: For the test option, the player will spawn into the Armoury allowing any item or weapon to be chosen or equipped, there is a connecting room with randomly spawned enemies allowing the player to test different play styles. 
- **in-game** For the in-game option, there will be either a random item spawn or a random enemy kill that allows the player to transport to the armoury room to select an item to assist them in defeating the boss.

# **Dependencies**

- Team 6 Map Generator
- Team 3 Item Generator
- Team 2 Weapon Generator

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Refactor map generator to be able to create a separate room that is isolated from the rest of the map (Oct. 13)
- [ ] Have the isolated armoury room spawn a version of each item and weapon (Oct. 13)
- [ ] Stop the items from despawning after one is selected from the room (Oct. 14)
- [ ] Create a second room adjacent to the armoury to be able to test the items against enemies (Oct. 15)
- [ ] Have the second room spawn different enemies each time (Oct. 15)

**Completion Deadline:** Oct. 17

# **Members**
- Sioryn Willett (@SIN-Willett)
- Liam Morris (@notinclined)

**Comment by iishiishii** [comment]
Link the dependencies to their associated feature/task tickets if possible. And remember to update documentation for the feature. Sub-features look good. This ticket is approved.
