### ISSUE TITLE
Map size scales by difficulty

### ISSUE THREAD

**Issue by IanP96** [UQcsse3200/2024-studio-1#469]
# **Description**
Map size is currently constant. Change this so that the harder the difficulty, the more rooms spawn.
- The current map size should correspond to Medium difficulty.
- Use the difficulty multiplier - lower multiplier gives higher difficulty.

## **Examples (optional)**
- Player wants an easy game. They select the Easy difficulty. The resulting number of rooms will be smaller than on other difficultues.

# **Dependencies**
None - all required code is present.

# **Milestones**
- [ ] Make map size scale (13 Oct)
- [ ] Unit tests (13 Oct)
- [ ] Manual testing using log output (13 Oct)
- [ ] PR (14 Oct)
- [ ] Documentation, update sprint form (14 Oct)

**Completion Deadline:** 14 Oct

# **Documentation**
In progress
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
- [User documentation](../wiki/Terrain)

# **Members**
Ian Pinto @IanP96
