### ISSUE TITLE
Minotaur Animation and sprite Sheet

### ISSUE THREAD

**Issue by rahulsagar500** [UQcsse3200/2024-studio-1#47]
# **Description**
**Task:** [Implement Animal Animations](#3).
**Feature:** [Animal Behavior and Attributes](#2)

This task is to implement the Minotaur and also create a sprite sheet for it ,  Then creating the MinotaurAnimationController with the help of NPC functions already present.
 
## **Example (optional)**
- **Part**: Depending on the task, you may want to provide some examples of how it would play out in the game.
- **Minotaur display **: Minotaur is an important entity in the game plan where it will be displayed and fully functioned in the game area for the player to fight with it.

# **Dependencies**
List any tasks on which this ticket relies. If there is already an existing ticket, reference it using #xx. If a task needs to be implemented, and the issue does not already exist, make a new ticket and leave it unassigned for someone else to take on. Ensure other team members are aware of the issue.

- [ ] Attacks being implemented(#32 )
- [ ] Movement patterns (#39 )

e.g.
- [ ]All the animations linked to Minotaur to be implemented in MainGameArea typically ( gesture , idle , walk , death).

 
# **Milestones**
List of steps that need to be completed for this task.
- [ ] Get All the animations created for Minotaur working (Aug. 20)

 
**Completion Deadline:** Aug. 20

 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)
- ...
 
# **Member**
- Rahul Sagar Pabba (rahulsagar500) (Slack Handle)
