### ISSUE TITLE
Refactor and Remove Code Smells from Weapon-Related Classes

### ISSUE THREAD

**Issue by thanghoang7020202** [UQcsse3200/2024-studio-1#484]
# **Description**
**Task:** [Refactor and Remove Code Smells from Weapon-Related Classes](#484)
**Feature:** [Polishing weapons](#415)

Refactor code to eliminate code smells in weapon-related classes, including `WeaponFactory`, `ProjectileFactory`, and files in the `weapon` folder (e.g., `FiringController.java`, `PositionTracker.java`, `WeaponAnimationController.java`) along with their respective test files.

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task:
- [x] Refactor `WeaponFactory` (Oct. 14)
- [x] Refactor `ProjectileFactory` (Oct. 14)
- [x] Refactor `FiringController.java` (Oct. 14)
- [x] Refactor `PositionTracker.java` (Oct. 14)
- [x] Refactor `WeaponAnimationController.java` (Oct. 14)
- [x] Refactor associated test files (Oct. 14)
- [ ] Test all classes after merge to main and ensure no code smells remain (Oct. 15)

**Completion Deadline:** Oct. 18

# **Documentation**
TBD

# **Members**
- Trong Hieu Mai (@Magnius001)
- Thang Hoang Cao Quoc (@thanghoang7020202)
