### ISSUE TITLE
Add missing animals to death screen and fix screen bugs

### ISSUE THREAD

**Issue by TriNhan-Pham** [UQcsse3200/2024-studio-1#499]
# **Description**
**Task:** [Add missing animals to death screen].

The task involves adding death screen for the new animals in the game such as Kitsune, Dragon, etc. Each animal should have a separate death screen and appear when the animal hit the character last.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix the bug of labels in the middle of the screen (Oct. 13)
- [x] Add all animals into death screen (Oct. 13)
- [x] Add background picture for animals into death screen (Oct. 14)
- [x] Remove background for animal pictures (Oct. 15)
 
**Completion Deadline:** Oct. 15
 
# **Documentation**
- Update the existing documentation in the wiki
 
# **Member**
- Tri Nhan Pham (@TriNhan-Pham)
