### ISSUE TITLE
Making player speed UI work with saving and loading

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#507]
# **Description**
**Task:** Making player speed UI work with saving and loading #507
**Feature:** Polishing items and improving builds #416

This task involves improving the player speed UI, which is currently represented as a progress bar (that shows the player's speed boost). Such improvements include setting the progress bar to the correct amount, after a player saves, then loads the game. 

 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Refactor progress bar implementation so that it can be set to the correct amount upon starting a game (Oct. 12)
- [x] Implement functionality that allows for easy access to player speed upon loading game (Oct. 13)
- [x] Manual testing (Oct. 14)
 
**Completion Deadline:** Oct. 14
 
# **Member**
- Jasmine (@Jas2310)
- Varun (@vsinh14)
