### ISSUE TITLE
Implementing builds task 

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#508]
# **Description**
**Task:** Implementing builds task #508
**Feature:** Polishing items and improving builds #416

This task involves implementing the 'builds' improvement of this sprint. As such, the items spawned in the Enemy Room should be unique to the character chosen. In particular, the "bear" and "necromancer" characters. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement a new method to obtain item specifications for the room, depending on the character chosen (Oct. 14)
- [x] Create different item specification lists depending on the character chosen (Oct. 14)
- [x] Manual testing (Oct. 15)
 
**Completion Deadline:** Oct. 15
 
# **Member**
- Jasmine (@Jas2310 )
- Cameron (@CameronBadman )
