### ISSUE TITLE
Enhance AITaskComponent for Target Dummy and Bear Trap

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#522]
# **Description**
**Task:** Enhance AITaskComponent for Target Dummy and Bear Trap #521
**Feature:** Polishing items and improving builds #416

This task focuses on enhancing the AITaskComponent to better manage enemy behaviors. Specifically, the task will prioritize the target dummy over the player, ensuring enemies will only switch their focus to the player if the dummy is destroyed or out of sight. Additionally, it introduces functionality to halt all current and queued tasks, allowing enemies to be immobilized when they trigger a bear trap.

# **Dependencies**
None
 
# **Milestones**
- [x] Update task prioritization to ensure the target dummy is targeted over the player
- [x] Implement a method to stop all current and upcoming priority tasks
- [x] Update relevant documentation
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
TBD

# **Member**
- Keagan Stoessel (@keagan-stoessel)
