### ISSUE TITLE
Armor Progress Bar UI Implementation

### ISSUE THREAD

**Issue by keagan-stoessel** [UQcsse3200/2024-studio-1#523]
# **Description**
**Task:** Armor Progress Bar UI Implementation #523
**Feature:** Polishing items and improving builds #416

This task involves enhancing the PlayerStatsDisplay by adding an armor progress bar that visually represents the player's current armor relative to the maximum armor capacity. The UI will be updated to include an armor icon and a corresponding progress bar.

# **Dependencies**
None
 
# **Milestones**
- [x] Add an event listener to update the armor bar based on player’s stats
- [x] Update UI to include armor icon and progress bar.
- [x] Implement armor progress bar to reflect current armor relative to max armor.
 
**Completion Deadline:** Oct. 14
 
# **Documentation**
TBD

# **Member**
- Keagan Stoessel (@keagan-stoessel)
