### ISSUE TITLE
Add Door Visual and Collision

### ISSUE THREAD

**Issue by s4693591** [UQcsse3200/2024-studio-1#53]
# **Description**
**Task:** [Add door visual and collision](#3).
**Feature:** [team-6-maps](#2)

Load in door item that when collided with it triggers an event that causes the player to transition to the relatively activated room. 
 
# **Dependencies**
Dependency on instantiation of changing room event that connects the correct rooms together with transition animation
 
# **Milestones**
- [ ] Item loads in (Aug. 20)
- [ ] Item has visuals (Aug. 20)
- [ ] Item placed correctly on map (Aug. 20)
- [ ] Item triggers a non-affecting event tbc (Aug. 20)
 
**Completion Deadline:** Aug. 20

# **Documentation**
- [Main description of feature](../wiki/Game-Screens) 
# **Member**
- Cooper Blackburn (@s4693591)

**Comment by s4693591** [comment]
This took longer than expected with checking colliding entities were the player. Though overvall all milestones were achieved
