### ISSUE TITLE
Gasoline

### ISSUE THREAD

**Issue by Mr-Plows** [UQcsse3200/2024-studio-1#544]
# **Description**
**Task:** [Gasoline](#3).
**Feature:**  Polishing items and improving builds #416 

This is a usable item that spawns multiple fire entities
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Create fire image and item icon (Oct. 14)
- [x] Spawn the fire entity (Oct. 15)
- [x] Spawn all of the entities around the player (Oct. 15)
 
**Completion Deadline:** Oct. 16
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
- [JavaDoc](JavaDoc/Location/Package/Class)

 
# **Member**
- Liam Morris(@notinclined)
