### ISSUE TITLE
Adding labels to buyable items

### ISSUE THREAD

**Issue by Jas2310** [UQcsse3200/2024-studio-1#545]
# **Description**
**Task:** Adding labels to buyable items #545
**Feature:** Polishing items and improving builds #416
This task involved creating "price tag" labels to each of the buyable items to show how much they cost. The labels should appear below the buyable items and should be visible to the player. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Creation of a new label (Oct. 10)
- [x] Label is correctly positioned to be below the buyable item (Oct. 10)
- [x] Label is removed when buyable item is removed (Oct. 11)
 
**Completion Deadline:** Oct. 11
 
# **Member**
- Jasmine (@Jas2310 )
