### ISSUE TITLE
Design and implement WeaponComponent (Aug. 22)

### ISSUE THREAD

**Issue by Magnius001** [UQcsse3200/2024-studio-1#55]
# **Description**
**Task:** [Design and implement weapon factory](#3).
**Feature:** [Weapons](#2)

We need to implement a factory pattern for creating various weapon features in the game. This factory will centralize the creation of weapon attributes like damage, range, fire rate, etc., allowing for easy extension and modification. The factory should return weapon features based on different input parameters, ensuring consistency and reusability across the game.
 
## **Example (optional)**
- **Input**: the factory will create a weapon with textures and characteristics correspond with the input weapon name.

# **Dependencies**
- #27 
- #33 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Design WeaponFactory to create Weapon entity (Aug. 22)
- [x] Implement components to handle attack and tracking player position (Aug. 23)
- [x] Add projectile component (Aug. 24)
 
**Completion Deadline:** Aug. 25
 
# **Documentation**
- [Main description of feature](../wiki/Game-Screens)
 
# **Member**
- Rohan Kumar (rohankumar17)
- Trong Hieu Mai (Magnius001)
- Cao Quoc Thang Hoang (thanghoang7020202)
- Divyansh Agarwal (divyanshddn146)
