### ISSUE TITLE
Bear trap and heart item changes 

### ISSUE THREAD

**Issue by Parasverma17** [UQcsse3200/2024-studio-1#560]
# **Description**
**Task:** Bear trap and heart item changes. (#560)
**Feature:** Polishing items and improving builds (#416 )

Refactor existing items, specifically the heart item and bear trap item, to improve functionality. For the bear trap, add a mechanism to immobilize enemies for a set duration and ensure it does not affect the Pet NPC. For the heart item, increase the maximum health limit to give players an additional advantage. Update the associated JavaDocs, UML diagrams, and sequence diagrams to reflect the changes made.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement functionality to immobilize enemies for a set duration (Oct. 13)
- [x] Modify the isEnemy() method to ensure the bear trap does not affect Pet NPCs. (Oct. 13)
- [x] Increase the maximum health limit of the heart item to 250 for player advantage. (Oct. 15)
- [x] Documentation and work on sequence, UML diagrams (Oct. 15)

# **Member**
- Paras Verma (@Parasverma17 )
