### ISSUE TITLE
Items

### ISSUE THREAD

**Issue by charlottemaherr** [UQcsse3200/2024-studio-1#6]
# **Description**
Design and implement various items for players to interact with on the map, which provide health and ability boosts in the game. These items should be scattered throughout the map, be visually distinct and easy to interact with. Each item has a unique effect on the player's health, attack or defence capabilities. The properties of these items (e.g. effect, boost amount, duration) should be editable. This feature adds an extra layer of depth to gameplay, encouraging users to make tactical decisions about when and where to use these items. By integrating these elements, we aim to increase player engagement. 

Note that this feature is related to the Weapons feature, as both involve player interactions with collectible objects in the game world. Ensure consistency in item handling and feedback mechanisms. 

## SubFeature/component
Health Packs: Restores a portion of the player's health upon use
- Available in various sizes (small/large) each offering different amounts of health restoration

Speed Boosts: Temporarily increases the player's movement speed 
- This item will be time-limited and can be used to escape danger, chase down animals or to move around the map more quickly

Shields: Provides temporary damage reduction/immunity 
- Shields can be activated to absorb damage for a short period, giving players a critical advantage in combat 

# **Dependencies**
- Level creation (#7)
- Player stats (e.g. health, movement speed) (#3)
- Weapons (#2)
- UI Design (Managing items in inventory) 

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #17
- [x] #81
- [x] Basic interaction with player: Player should be able to have some basic interaction with the items, however, no effect on the player yet (e.g. item disappears if player touches it) (Aug. 28)

**Completion Deadline:** Aug. 29

# **Extras**
- [ ] Storage (require hot bar or inventory if player wishes to store the item for later use) This will likely be implemented in a future sprint but worth noting. 
- [ ] Implement item effects on player health/stats 

# **Documentation**
TBD

# **Members**
- Jasmine Hong (@Jas2310 )
- Charlotte Maher (@charlottemaherr ) 
- Paras Verma (@Parasverma17 ) 
- Keagan Stoessel (@keagan-stoessel ) 
- Divyanshu (@Div1o1 )

**Comment by The-AhmadAA** [comment]
Use the linking feature to link dependencies and subtasks to their associated feature/task tickets. Otherwise looking good so far, make sure to update it with links to the task tickets and documentation as they are created. This ticket is approved and you can start creating the associated task tickets.
