### ISSUE TITLE
Integrate mechanics that put weapons into inventory (Aug. 23)

### ISSUE THREAD

**Issue by thanghoang7020202** [UQcsse3200/2024-studio-1#66]
# **Description**
**Task:** [Integrate mechanics that put weapons into inventory](#66).
**Feature:** [Weapon] (#2)

This task involves integrating the weapon mechanics into the existing inventory system. The goal is to allow players to collect, store, and manage weapons within their inventory. 
 
## **Example (optional)**
- **Weapon Storage**: Implement functionality to store collected weapons in the player's inventory.
- ** Weapon Switching**: Enable players to switch to new weapons during when touch the weapon on the ground.

# **Dependencies**
- [x] Inventory System and character (#3)

- [x] Weapon(#2 )
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Implement weapon storage in the inventory
- [x] Develop equip/unequip functionality
 
**Completion Deadline:** Aug. 24
 
# **Documentation**

# **Member**
- Cao Quoc Thang Hoang ([thanghoang7020202](https://github.com/thanghoang7020202))
