### ISSUE TITLE
Invincibility Frames

### ISSUE THREAD

**Issue by Jordamnmn** [UQcsse3200/2024-studio-1#67]
# **Description**
**Task:** [Invincibility Frames](#3).
**Feature:** [Character](#3)

The character will have an amount of frames after getting hit in which they can't be hit by any source of damage. Whenever the player is hit, their amount of invincibility frames will be checked for being greater than 0. If it is then they won't get hit, otherwise they will gain the frames. The amount of invincibility gained will be discussed with the design committee 

# **Dependencies**
None

# **Milestones**
List of steps that need to be completed for this task.
- [x] Understand engine (Aug. 22)
- [x] Implement feature (Aug. 27)
 
#**Optional**
- [x] Add animation to the character while invincible
**Completion Deadline:** Aug. 27

# **Documentation**
- [Invincibility Frames](../wiki/Player)
 
# **Member**
- Jordan Cole (Jordamnmn)
