### ISSUE TITLE
MAPS -Team 6

### ISSUE THREAD

**Issue by AElanagai** [UQcsse3200/2024-studio-1#9]
# **Description**
The map system in our game will consist of two main components: the Map Builder and the Map Executor. The Map Builder is responsible for creating the layout of the game, including rooms, animals, items, and the ending room. The Map Executor will take the decisions made by the Map Builder and display the corresponding data in each room. This feature will involve significant collaboration with other groups to ensure seamless integration and functionality

## SubFeature/component (optional)
Map Builder
Room Mapping: Define the layout and connections between various rooms.
Animal Placement: Randomly or strategically place animals in specific rooms.
Item Placement: Distribute items throughout the map.
Ending Room Designation: Identify and configure the final room in the game.
Map Executor
Data Display: Render the data for each room, including animals and items.
Room Transition: Handle the logic for moving between rooms.
Interaction Handling: Manage interactions between the player and the elements in the room (e.g., animals, items).

## **Examples (optional)**
The Map Builder creates a dungeon with like 15 interconnected rooms, places a bird in room 5, a short gun or the broken bottle in room 3, and designates room 10 as the ending room.
# **Dependencies**

<<I DONT HAVE A CLEAR IDEA FOR NOW>>

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [x] #13
- [x] design beta_map (for dependancies) [15]
- [x] Development of map executor importer [15 Aug]
- [x] #14
- [x]  Development of #28 
- [x] Development of map executor graphical module [ 21 Aug]
- [x] integration with entities on the graphical module [ 25 Aug ]
- [x] Integration testing and unit testing [ 26 Aug ] 
- [x] Final view and merging [ 27 Aug] 

**Completion Deadline: [28 Aug]** 

# **Extras (optional)**
- [ ] Random deterministic Map Generation: Implement a feature for generating random maps to increase replayability.
- [ ] map saves: implement a method to access and import map saves 

# **Documentation**
- [Main description of feature](../wiki/Entity-Component-System-(ECS))
<<have to add our repo wiki and stuff here>>

# **Members**
- Name (GitHub Username) (Slack Handle) -- only one is needed if they are the same.
- Elanagai Arivuchelvan (@AElanagai )(Ela)
- Cameron Badman(@CameronBadman)(Cameron Badman No risk man :() 
- Kai Kliewer(@daggerofthemind)(Kai)
- Dhruv Anil (@dhruvanil55) (Dhruv)

**Comment by The-AhmadAA** [comment]
This ticket is looking good so far, make sure to update it with links to the task tickets and documentation as they are created. This ticket is approved and you can start creating the associated task tickets. Please update with dependencies as you discover them, if you have any.
