### ISSUE TITLE
Collectible Factory

### ISSUE THREAD

**Issue by SIN-Willett** [UQcsse3200/2024-studio-1#94]
# **Description**
**Task:** [Collectible Factory](#94).
**Features:** #6 #3

A collaborative effort between the Character and Item teams to get collectible items to be creatable from a factory, and collectable by a player.
 
## **Example (optional)**
A medkit might spawn on the ground that the player can pickup and use.
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Collectible Factory needs to be created.
- [x] Item and Weapon factories need to be created and incorporated into CollectibleFactory.
- [x] Collectibles need to be given a means to be spawned into the world and have "pickup" collision with the player.
 
**Completion Deadline:** Aug. 23

e.g.
- [x] Initial design of `CollectibleFactory` created and documented on wiki.
- [x] Unit tests implemented for `CollectibleFactory`.
- [x] `CollectibleFactory` class implemented and tested.
- [x] Documentation of `CollectibleFactory` updated on wiki.
 
# **Documentation**
- [JavaDoc](JavaDoc/com/csse3200/game/entities/factories/CollectibleFactory)
- ...
 
# **Member**
- Sioryn (@SIN-Willett) (SINWillett)
- Jas (@Jas2310) (Jas)
